// ZMK Studio verify script for evolved V2 layout
window.CHARYBDIS_VERSION = "evolved-v2";

function getKeyBinding(layer, x, y) {
  const btn = document.querySelector(`[data-layer='${layer}'][data-x='${x}'][data-y='${y}']`);
  if (!btn) return null;
  const behavior = btn.querySelector('.behavior-name')?.textContent?.trim() || '';
  const parameter = btn.querySelector('.parameter-name')?.textContent?.trim() || '';
  const modifiers = Array.from(btn.querySelectorAll('.modifier-tag')).map(m => m.textContent.trim()).join('+');
  return {behavior, parameter, modifiers};
}

const EXPECTED_CSV = `"layer","x","y","label","behavior","parameter","modifiers"
"0","0","0","Esc","Key Press","Escape",""
"0","1","0","1","Key Press","1 and Bang",""
"0","2","0","2","Key Press","2 and At",""
"0","3","0","3","Key Press","3 and Hash",""
"0","4","0","4","Key Press","4 and Dollar",""
"0","5","0","5","Key Press","5 and Percent",""
"0","7","0","6","Key Press","6 and Caret",""
"0","8","0","7","Key Press","7 and Ampersand",""
"0","9","0","8","Key Press","8 and Star",""
"0","10","0","9","Key Press","9 and Left Bracket",""
"0","11","0","0","Key Press","0 and Right Bracket",""
"0","12","0","BkSp","Key Press","Delete",""
"0","0","1","Tab","Key Press","Tab",""
"0","1","1","Q","Key Press","Q",""
"0","2","1","W","Key Press","W",""
"0","3","1","E","Key Press","E",""
"0","4","1","R","Key Press","R",""
"0","5","1","T","Key Press","T",""
"0","7","1","Y","Key Press","Y",""
"0","8","1","U","Key Press","U",""
"0","9","1","I","Key Press","I",""
"0","10","1","O","Key Press","O",""
"0","11","1","P","Key Press","P",""
"0","12","1","å","Key Press","Left Brace",""
"0","0","2","Shft","Key Press","LeftShift",""
"0","1","2","A","Key Press","A",""
"0","2","2","S","Key Press","S",""
"0","3","2","D","Key Press","D",""
"0","4","2","F","Key Press","F",""
"0","5","2","G","Key Press","G",""
"0","7","2","H","Key Press","H",""
"0","8","2","J","Key Press","J",""
"0","9","2","K","Key Press","K",""
"0","10","2","L","Key Press","L",""
"0","11","2","ø","Key Press","SemiColon and Colon",""
"0","12","2","æ","Key Press","Left Apos and Double",""
"0","0","3","Ctrl","Key Press","LeftControl",""
"0","1","3","Z","Key Press","Z",""
"0","2","3","X","Key Press","X",""
"0","3","3","C","Key Press","C",""
"0","4","3","V","Key Press","V",""
"0","5","3","B","Key Press","B",""
"0","7","3","N","Key Press","N",""
"0","8","3","M","Key Press","M",""
"0","9","3",",","Key Press","Comma and LessThan",""
"0","10","3",".","Key Press","Period and GreaterThan",""
"0","11","3","/","Key Press","ForwardSlash and QuestionMark",""
"0","12","3","\","Key Press","Backslash and Pipe",""
"0","3","4","Nav","coach_l1_hold","",""
"0","4","4","␣","Key Press","Spacebar",""
"0","5","4","Ctrl+5","Key Press","5 and Percent","L Ctrl"
"0","7","4","System","coach_l4_hold","",""
"0","8","4","Window","coach_l3_hold","",""
"0","4","5","Ctrl+K Ctrl+S","Key Press","S","L Ctrl+K+L Ctrl"
"0","5","5","Mouse","coach_l2_hold","",""
"0","7","5","Ret","Key Press","Return Enter",""
"1","0","0","Win+B","Key Press","B","L GUI"
"1","2","0","Ctrl+S","Key Press","S","L Ctrl"
"1","3","0","Ctrl+Alt+Down","Key Press","DownArrow","L Ctrl+L Alt"
"1","4","0","Win+I","Key Press","I","L GUI"
"1","5","0","Ctrl+Enter","Key Press","Return Enter","L Ctrl"
"1","7","0","Shift+Enter","Key Press","Return Enter","L Shift"
"1","8","0","Ctrl+V","Key Press","V","L Ctrl"
"1","9","0","Ctrl+Alt+Up","Key Press","UpArrow","L Ctrl+L Alt"
"1","10","0","Alt+F12","Key Press","F12","L Alt"
"1","0","1","Code","Toggle Layer","Layer::5",""
"1","1","1","F1","Key Press","F1",""
"1","2","1","Ctrl+K Ctrl+W","Key Press","W","L Ctrl+K+L Ctrl"
"1","3","1","Win+3","Key Press","3 and Hash","L GUI"
"1","4","1","Shift+Alt+Left","Key Press","LeftArrow","L Shift+L Alt"
"1","5","1","Win+D","Key Press","D","L GUI"
"1","7","1","Ctrl+Shift+T","Key Press","T","L Ctrl+L Shift"
"1","8","1","Ctrl+Left","Key Press","LeftArrow","L Ctrl"
"1","9","1","Ctrl+J","Key Press","J","L Ctrl"
"1","10","1","Ctrl+Shift+C","Key Press","C","L Ctrl+L Shift"
"1","11","1","Ctrl+Right","Key Press","RightArrow","L Ctrl"
"1","12","1","Ctrl+Space","Key Press","Spacebar","L Ctrl"
"1","0","2","Ctrl+G","Key Press","G","L Ctrl"
"1","1","2","Ctrl+Shift+9","Key Press","9 and Left Bracket","L Ctrl+L Shift"
"1","2","2","Win+Down","Key Press","DownArrow","L GUI"
"1","3","2","Win+Shift+Right","Key Press","RightArrow","L GUI+L Shift"
"1","4","2","Win+Right","Key Press","RightArrow","L GUI"
"1","5","2","Ctrl+B","Key Press","B","L Ctrl"
"1","7","2","Ctrl+Shift+D","Key Press","D","L Ctrl+L Shift"
"1","8","2","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"1","9","2","MB1","Mouse Key Press","MB1",""
"1","10","2","→","Key Press","RightArrow",""
"1","11","2","Ctrl+End","Key Press","End","L Ctrl"
"1","12","2","Ctrl+K","Key Press","K","L Ctrl"
"1","1","3","Ctrl+8","Key Press","8 and Star","L Ctrl"
"1","2","3","RightArrow","Key Press","RightArrow",""
"1","3","3","?","Key Press","?",""
"1","4","3","Up","Key Press","UpArrow",""
"1","5","3","Win+Ctrl+Left","Key Press","LeftArrow","L GUI+L Ctrl"
"1","7","3","C","Key Press","C","L Ctrl"
"1","8","3","Ctrl+Home","Key Press","Home","L Ctrl"
"1","9","3","coach_game_lock","coach_game_lock","",""
"1","10","3","Ctrl+Shift+End","Key Press","End","L Ctrl+L Shift"
"1","11","3","MB3","Mouse Key Press","MB3",""
"1","3","4","Win+N","Key Press","N","L GUI"
"1","4","4","Win+C","Key Press","C","L GUI"
"1","7","4","Ctrl+F","Key Press","F","L Ctrl"
"1","8","4","UpArrow","Key Press","UpArrow",""
"1","4","5","Shift+F3","Key Press","F3","L Shift"
"1","5","5","Ctrl+-","Key Press","Dash and Underscore","L Ctrl"
"1","7","5","Ctrl+Shift+\","Key Press","Backslash and Pipe","L Ctrl+L Shift"
"2","0","0","Snip","Key Press","PrintScreen","L GUI+L Shift"
"2","1","0","f9","Key Press","F9",""
"2","2","0","Desktop","Key Press","D","L GUI"
"2","3","0","Alt+Shift+Up","Key Press","UpArrow","L Alt+L Shift"
"2","4","0","ScrollUp","Key Press","ScrollUp",""
"2","5","0","Ctrl+Shift+6","Key Press","6 and Caret","L Ctrl+L Shift"
"2","7","0","Ctrl+P","Key Press","P","L Ctrl"
"2","8","0","Ctrl+C","Key Press","C","L Ctrl"
"2","9","0","Ctrl+1","Key Press","1 and Bang","L Ctrl"
"2","10","0","Shift+F11","Key Press","F11","L Shift"
"2","11","0","ScrollDown","Key Press","ScrollDown",""
"2","0","1","Win+E","Key Press","E","L GUI"
"2","1","1","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"2","2","1","Close","Key Press","W","L Ctrl"
"2","3","1","Alt+P","Key Press","P","L Alt"
"2","4","1","Ctrl+Shift+$","Key Press","$","L Ctrl+L Shift"
"2","5","1","Ctrl+Click","Key Press","Click","L Ctrl"
"2","7","1","Ctrl+Shift+!","Key Press","!","L Ctrl+L Shift"
"2","8","1","F9","Key Press","F9",""
"2","9","1","MB4","Mouse Key Press","MB4",""
"2","10","1","minus","Key Press","Dash and Underscore",""
"2","11","1","Ctrl+D","Key Press","D","L Ctrl"
"2","12","1","Alt+Up","Key Press","UpArrow","L Alt"
"2","0","2","Win+B","Key Press","B","L GUI"
"2","1","2","Win+Shift+S","Key Press","S","L GUI+L Shift"
"2","2","2","Win+Shift+Left","Key Press","LeftArrow","L GUI+L Shift"
"2","3","2","Ctrl+.","Key Press","Period and GreaterThan","L Ctrl"
"2","4","2","Ctrl+Shift+>","Key Press",">","L Ctrl+L Shift"
"2","5","2","Ctrl+Shift+Down","Key Press","DownArrow","L Ctrl+L Shift"
"2","7","2","Ctrl+Shift+A","Key Press","A","L Ctrl+L Shift"
"2","8","2","Ctrl+Shift+`","Key Press","`","L Ctrl+L Shift"
"2","9","2","coach_travel_toggle","coach_travel_toggle","",""
"2","10","2","Ctrl+Y","Key Press","Y","L Ctrl"
"2","11","2","Ctrl+Shift+X","Key Press","X","L Ctrl+L Shift"
"2","12","2","F12","Key Press","F12",""
"2","1","3","Page Down","Key Press","DownArrow","Page"
"2","2","3","Shift+Alt+A","Key Press","A","L Alt+L Shift"
"2","3","3","Win+A","Key Press","A","L GUI"
"2","4","3","Win+Ctrl+F4","Key Press","F4","L GUI+L Ctrl"
"2","5","3","Win+V","Key Press","V","L GUI"
"2","7","3","Shift+Alt+Down","Key Press","DownArrow","L Alt+L Shift"
"2","8","3","Ctrl+Shift+Home","Key Press","Home","L Ctrl+L Shift"
"2","9","3","Ctrl+Shift+Up","Key Press","UpArrow","L Ctrl+L Shift"
"2","10","3","Ctrl+I","Key Press","I","L Ctrl"
"2","11","3","Alt+Shift+-","Key Press","-","L Alt+L Shift"
"2","12","3","MB2","Mouse Key Press","MB2",""
"2","3","4","Ctrl+Page Up","Key Press","PageUp","L Ctrl"
"2","4","4","Ctrl+X","Key Press","X","L Ctrl"
"2","7","4","forwardslash_combo","Key Press","ForwardSlash and QuestionMark",""
"2","8","4","left brace_combo","Key Press","Left Brace",""
"2","4","5","Ctrl+[","Key Press","Left Brace","L Ctrl"
"2","7","5","=","Key Press","=",""
"3","0","0","Alt+Home","Key Press","Home","L Alt"
"3","1","0","Ctrl+Shift+Tab","Key Press","Tab","L Ctrl+L Shift"
"3","2","0","Ctrl+Shift+F5","Key Press","F5","L Ctrl+L Shift"
"3","3","0","Emoji","Key Press","Period and GreaterThan","L GUI"
"3","4","0","QSett","Key Press","A","L GUI"
"3","5","0","Notif","Key Press","N","L GUI"
"3","7","0","Alt+Right","Key Press","RightArrow","L Alt"
"3","9","0","Ctrl+W","Key Press","W","L Ctrl"
"3","10","0","Shift+Tab","Key Press","Tab","L Shift"
"3","11","0","Ctrl+Z","Key Press","Z","L Ctrl"
"3","12","0","Ctrl+`","Key Press","`","L Ctrl"
"3","0","1","BT1","Bluetooth","BT_SEL 1",""
"3","1","1","Ctrl+F6","Key Press","F6","L Ctrl"
"3","2","1","Shift+Click","Key Press","Click","L Shift"
"3","3","1","→","Key Press","RightArrow","L GUI"
"3","4","1","Win+Ctrl+D","Key Press","D","L GUI+L Ctrl"
"3","5","1","Ctrl+Shift+Esc","Key Press","Escape","L Ctrl+L Shift"
"3","7","1","Ctrl+L","Key Press","L","L Ctrl"
"3","8","1","Ctrl+T","Key Press","T","L Ctrl"
"3","9","1","F10","Key Press","F10",""
"3","10","1","Ctrl+O","Key Press","O","L Ctrl"
"3","11","1","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"3","12","1","Ctrl+H","Key Press","H","L Ctrl"
"3","0","2","Ctrl+Shift+W","Key Press","W","L Ctrl+L Shift"
"3","2","2","Ctrl+Shift+P","Key Press","P","L Ctrl+L Shift"
"3","3","2","1","Key Press","1 and Bang","L GUI"
"3","4","2","Win+Space","Key Press","Spacebar","L GUI"
"3","5","2","5","Key Press","5 and Percent","L GUI"
"3","7","2","Ctrl+Up","Key Press","UpArrow","L Ctrl"
"3","8","2","Ctrl+Shift+C","Key Press","C","L Ctrl+L Shift"
"3","9","2","Ctrl+K S","Key Press","S","L Ctrl+K"
"3","10","2","Shift+F5","Key Press","F5","L Shift"
"3","11","2","Ctrl+N","Key Press","N","L Ctrl"
"3","12","2","Ctrl+Shift+<","Key Press","<","L Ctrl+L Shift"
"3","0","3","Alt+Shift+D","Key Press","D","L Alt+L Shift"
"3","1","3","Ctrl+Shift+%","Key Press","%","L Ctrl+L Shift"
"3","3","3","Ctrl+Page Up","Key Press","UpArrow","L Ctrl+Page"
"3","4","3","Ctrl+Shift+G","Key Press","G","L Ctrl+L Shift"
"3","5","3","Alt+Tab","Key Press","Tab","L Alt"
"3","7","3","Ctrl+Down","Key Press","DownArrow","L Ctrl"
"3","8","3","Ctrl+Y","Key Press","Y","L Ctrl"
"3","9","3","BT3","Bluetooth","BT_SEL 3",""
"3","10","3","gi","Key Press","gi",""
"3","11","3","Alt+Shift+Down","Key Press","DownArrow","L Alt+L Shift"
"3","12","3","Ctrl+Shift+N","Key Press","N","L Ctrl+L Shift"
"3","3","4","Alt+=","Key Press","=","L Alt"
"3","4","4","Win+M","Key Press","M","L GUI"
"3","4","5","Win+E","Key Press","E","L GUI"
"3","7","5","Ctrl+\","Key Press","Backslash and Pipe","L Ctrl"
"4","0","0","BT0","Bluetooth","BT_SEL 0",""
"4","1","0","BT1","Bluetooth","BT_SEL 1",""
"4","2","0","Ctrl+Shift+F","Key Press","F","L Ctrl+L Shift"
"4","3","0","Ctrl+A","Key Press","A","L Ctrl"
"4","4","0","BT4","Bluetooth","BT_SEL 4",""
"4","5","0","Win+Up","Key Press","UpArrow","L GUI"
"4","7","0","Ctrl+Shift+X","Key Press","X","L Ctrl+L Shift"
"4","8","0","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"4","10","0","Studio Unlock","Studio Unlock","",""
"4","11","0","Win+K","Key Press","K","L GUI"
"4","12","0","Alt+Enter","Key Press","Return Enter","L Alt"
"4","0","1","Ctrl+G","Key Press","G","L Ctrl"
"4","1","1","Ctrl+O","Key Press","O","L Ctrl"
"4","2","1","Ctrl+Q","Key Press","Q","L Ctrl"
"4","3","1","Ctrl+Shift++","Key Press","Shift","L Ctrl"
"4","4","1","Shift+Alt+Right","Key Press","RightArrow","L Shift+L Alt"
"4","5","1","Ctrl+Page Down","Key Press","DownArrow","L Ctrl+Page"
"4","7","1","Ctrl+S","Key Press","S","L Ctrl"
"4","8","1","Ctrl+E","Key Press","E","L Ctrl"
"4","9","1","Ctrl+[","Key Press","[","L Ctrl"
"4","10","1","Ctrl+Shift+N","Key Press","N","L Ctrl+L Shift"
"4","11","1","Ctrl+Shift+U","Key Press","U","L Ctrl+L Shift"
"4","12","1","Ctrl+]","Key Press","]","L Ctrl"
"4","0","2","Ctrl+R","Key Press","R","L Ctrl"
"4","1","2","Win+Tab","Key Press","Tab","L GUI"
"4","2","2","Alt+Shift","Key Press","Shift","L Alt"
"4","3","2","Win+Left","Key Press","LeftArrow","L GUI"
"4","4","2","Ctrl+G","Key Press","G","L Ctrl"
"4","5","2","right bracket","Key Press","Right Brace",""
"4","8","2","Ctrl+K Ctrl+F","Key Press","F","L Ctrl+K+L Ctrl"
"4","9","2","Ctrl+Tab","Key Press","Tab","L Ctrl"
"4","10","2","Alt+Down","Key Press","DownArrow","L Alt"
"4","11","2","Ctrl+Shift+Z","Key Press","Z","L Ctrl+L Shift"
"4","12","2","Ctrl+Shift+F6","Key Press","F6","L Ctrl+L Shift"
"4","0","3","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"4","1","3","Shift+Alt+Up","Key Press","UpArrow","L Alt+L Shift"
"4","2","3","DownArrow","Key Press","DownArrow",""
"4","3","3","Ctrl+D","Key Press","D","L Ctrl"
"4","4","3","Win+2","Key Press","2 and At","L GUI"
"4","5","3","Ctrl+;","Key Press","SemiColon and Colon","L Ctrl"
"4","7","3","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"4","8","3","Ctrl+Shift+Left","Key Press","LeftArrow","L Ctrl+L Shift"
"4","9","3","f11","Key Press","F11",""
"4","10","3","Ctrl+Shift+Del","Key Press","Del","L Ctrl+L Shift"
"4","11","3","Alt+Click","Key Press","Click","L Alt"
"4","12","3","Accept","Key Press","A","L Ctrl+L Shift"
"4","3","4","Ctrl+Tab","Key Press","Tab","L Ctrl"
"4","4","4","Ctrl+Shift+Right","Key Press","RightArrow","L Ctrl+L Shift"
"4","5","4","Alt+Shift++","Key Press","Shift","L Alt"
"4","7","4","Shift+Alt+Down","Key Press","DownArrow","L Shift+L Alt"
"4","8","4","f9","Key Press","F9",""
"4","4","5","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"4","5","5","forwardslash_combo","Key Press","ForwardSlash and QuestionMark",""
"5","0","0","Ctrl+Shift+O","Key Press","O","L Ctrl+L Shift"
"5","2","0","gg","Key Press","gg",""
"5","4","0","GoSym","Key Press","O","L Ctrl+L Shift"
"5","5","0","Win+X","Key Press","X","L GUI"
"5","7","0","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"5","8","0","Ctrl+G","Key Press","G","L Ctrl"
"5","9","0","Up","Key Press","UpArrow",""
"5","10","0","Ctrl+U","Key Press","U","L Ctrl"
"5","0","1","Wrap","Key Press","Z","L Alt"
"5","1","1","Ctrl+Shift+F","Key Press","F","L Ctrl+L Shift"
"5","2","1","Win+;","Key Press","SemiColon and Colon","L GUI"
"5","3","1","Ctrl+Shift+J","Key Press","J","L Ctrl+L Shift"
"5","4","1","Win+L","Key Press","L","L GUI"
"5","5","1","Ctrl+Shift+`","Key Press","Grave Accent and Tilde","L Ctrl+L Shift"
"5","7","1","Ctrl+Shift+I","Key Press","I","L Ctrl+L Shift"
"5","8","1","LeftArrow","Key Press","LeftArrow",""
"5","9","1","Ctrl+M","Key Press","M","L Ctrl"
"5","10","1","f1","Key Press","F1",""
"5","11","1","Ctrl+Shift+R","Key Press","R","L Ctrl+L Shift"
"5","0","2","Ctrl+Shift+Enter","Key Press","Return Enter","L Ctrl+L Shift"
"5","1","2","Save","Key Press","S","L Ctrl"
"5","2","2","Ctrl+J","Key Press","J","L Ctrl"
"5","3","2","Win+.","Key Press","Period and GreaterThan","L GUI"
"5","4","2","Ctrl++","Key Press","LeftControl",""
"5","5","2","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"5","9","2","Ctrl+L","Key Press","L","L Ctrl"
"5","10","2","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"5","11","2","coach_travel_toggle","coach_travel_toggle","",""
"5","12","2","F11","Key Press","F11",""
"5","1","3","Alt+F","Key Press","F","L Alt"
"5","3","3","NTerm","Key Press","Grave Accent and Tilde","L Ctrl+L Shift"
"5","4","3","Ctrl+Shift+~","Key Press","~","L Ctrl+L Shift"
"5","5","3","f8","Key Press","F8",""
"5","10","3","keypad 3","Key Press","3 and PageDn",""
"5","3","4","Base","coach_base","",""
"6","2","0","Shift+Delete","Key Press","Dash and Underscore","L Shift"
"6","3","0","Alt+=","Key Press","Equals and Plus","L Alt"
"6","4","0","Ctrl+Left","Key Press","LeftArrow","L Ctrl"
"6","7","0","Ctrl+Shift+1","Key Press","1 and Bang","L Ctrl+L Shift"
"6","8","0","Ctrl+Q","Key Press","Q","L Ctrl"
"6","10","0","Ctrl+3","Key Press","3 and Hash","L Ctrl"
"6","2","1","Ctrl+Space","Key Press","Spacebar","L Ctrl"
"6","3","1","F10","Key Press","F10",""
"6","4","1","Win+Shift+Left","Key Press","LeftArrow","L GUI+L Shift"
"6","5","1","Ctrl+Right","Key Press","RightArrow","L Ctrl"
"6","7","1","Ctrl+Shift+R","Key Press","R","L Ctrl+L Shift"
"6","8","1","Alt+Right","Key Press","RightArrow","L Alt"
"6","9","1","Ctrl+5","Key Press","5 and Percent","L Ctrl"
"6","10","1","Ctrl+Shift+Left","Key Press","LeftArrow","L Ctrl+L Shift"
"6","1","2","Shift+F8","Key Press","F8","L Shift"
"6","2","2","F9","Key Press","F9",""
"6","4","2","Alt+F4","Key Press","F4","L Alt"
"6","5","2","Ctrl+,","Key Press","Comma and LessThan","L Ctrl"
"6","8","2","Ctrl+Shift+2","Key Press","2 and At","L Ctrl+L Shift"
"6","9","2","Win+N","Key Press","N","L GUI"
"6","10","2","Ctrl+Alt+Down","Key Press","DownArrow","L Alt+L Ctrl"
"6","11","2","Ctrl+Shift+Up","Key Press","UpArrow","L Ctrl+L Shift"
"6","2","3","Win+P","Key Press","P","L GUI"
"6","3","3","Shift+F11","Key Press","F11","L Shift"
"6","4","3","Win+Shift+Right","Key Press","RightArrow","L GUI+L Shift"
"6","5","3","F4","Key Press","F4",""
"6","7","3","Ctrl+F5","Key Press","F5","L Ctrl"
"6","8","3","Shift+Alt+A","Key Press","A","L Shift+L Alt"
"6","9","3","Ctrl+6","Key Press","6 and Caret","L Ctrl"
"6","10","3","Ctrl+-","Key Press","-","L Ctrl"
"6","4","4","Ctrl+0","Key Press","0 and Right Bracket","L Ctrl"
"6","7","4","MB5","Mouse Key Press","MB5",""
"7","1","1","9 PU","Key Press","9 and PageUp",""
"7","2","1","UpArrow","Key Press","UpArrow",""
"7","3","1","3 PD","Key Press","3 and PageDn",""
"7","9","1","3 PD","Key Press","3 and PageDn",""
"7","10","1","UpArrow","Key Press","UpArrow",""
"7","11","1","9 PU","Key Press","9 and PageUp",""
"7","1","2","LeftArrow","Key Press","LeftArrow",""
"7","2","2","DownArrow","Key Press","DownArrow",""
"7","3","2","RightArrow","Key Press","RightArrow",""
"7","4","2","Z","Key Press","Z",""
"7","8","2","Z","Key Press","Z",""
"7","9","2","LeftArrow","Key Press","LeftArrow",""
"7","10","2","DownArrow","Key Press","DownArrow",""
"7","11","2","RightArrow","Key Press","RightArrow",""
"7","1","3","X","Key Press","X",""
"7","2","3","C","Key Press","C",""
"7","3","3","Shft","Key Press","LeftShift",""
"7","4","3","Esc","Key Press","Escape",""
"7","8","3","Esc","Key Press","Escape",""
"7","9","3","Shft","Key Press","LeftShift",""
"7","10","3","C","Key Press","C",""
"7","11","3","X","Key Press","X",""
"7","3","4","Exit Base","coach_base","",""
"7","4","4","␣","Key Press","Spacebar",""
"7","5","4","Exit Base","coach_base","",""
"7","7","4","Exit Base","coach_base","",""
"7","8","4","Exit Base","coach_base","",""
"7","4","5","Click","Mouse Key Press","default_transform",""
"7","5","5","Right Click","Mouse Key Press","default_transform",""
"7","7","5","Ret","Key Press","Return Enter",""
"8","4","0","Win+5","Key Press","5 and Percent","L GUI"
"8","8","0","Shift+Space","Key Press","Spacebar","L Shift"
"8","10","0","Alt+D","Key Press","D","L Alt"
"8","12","0","Ctrl+/","Key Press","ForwardSlash and QuestionMark","L Ctrl"
"8","0","1","Down","Key Press","DownArrow",""
"8","2","1","F11","Key Press","F11",""
"8","3","1","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"8","4","1","Ctrl+0","Key Press","0 and Right Bracket","L Ctrl"
"8","5","1","Win+Ctrl+Right","Key Press","RightArrow","L Ctrl+L GUI"
"8","7","1","Ctrl+Shift+Esc","Key Press","Escape","L Ctrl+L Shift"
"8","8","1","Alt+Left","Key Press","LeftArrow","L Alt"
"8","9","1","F5","Key Press","F5",""
"8","10","1","Ctrl+Shift+B","Key Press","B","L Ctrl+L Shift"
"8","2","2","F2","Key Press","F2",""
"8","4","2","Win+Home","Key Press","Home","L GUI"
"8","7","2","Ctrl+4","Key Press","4 and Dollar","L Ctrl"
"8","8","2","Alt+F4","Key Press","F4","L Alt"
"8","9","2","Ctrl+2","Key Press","2 and At","L Ctrl"
"8","10","2","Ctrl+End","Key Press","End","L Ctrl"
"8","1","3","Ctrl+Shift+Q","Key Press","Q","L Ctrl+L Shift"
"8","3","3","Ctrl+Shift+B","Key Press","B","L Ctrl+L Shift"
"8","4","3","Win+4","Key Press","4 and Dollar","L GUI"
"8","5","3","Win+.","Key Press","Period and GreaterThan","L GUI"
"8","7","3","Win+;","Key Press","SemiColon and Colon","L GUI"
"8","8","3","Alt+Up","Key Press","UpArrow","L Alt"
"8","9","3","Ctrl+Home","Key Press","Home","L Ctrl"
"8","3","4","Win+T","Key Press","T","L GUI"
"8","4","4","Ctrl+7","Key Press","7 and Ampersand","L Ctrl"
"8","7","4","Exit Travel","coach_travel_off","",""
"8","4","5","Delete","Key Press","Delete",""
"8","5","5","Win+Ctrl+Right","Key Press","RightArrow","L GUI+L Ctrl"
"9","0","0","Shift+Alt+Up","Key Press","UpArrow","L Shift+L Alt"
"9","4","0","Ctrl+End","Key Press","End","L Ctrl"
"9","8","0","Ctrl+Up","Key Press","UpArrow","L Ctrl"
"9","9","0","F8","Key Press","F8",""
"9","0","1","f2","Key Press","F2",""
"9","1","1","WfSt","Key Press","W","L Ctrl+L Shift"
"9","2","1","Asgn","Key Press","A","L Ctrl+L Shift"
"9","4","1","Fav","Key Press","M","L Ctrl"
"9","5","1","List","Key Press","1 and Bang","L Ctrl"
"9","7","1","Ctrl+6","Key Press","6 and Caret","L Ctrl"
"9","8","1","Shift+Alt+Down","Key Press","DownArrow","L Alt+L Shift"
"9","10","1","Ctrl+Shift+;","Key Press","SemiColon and Colon","L Ctrl+L Shift"
"9","0","2","pageup","Key Press","9 and PageUp",""
"9","1","2","Ctrl+9","Key Press","9 and Left Bracket","L Ctrl"
"9","2","2","ChkIn","Key Press","E","L Ctrl+L Shift"
"9","4","2","Win+Tab","Key Press","Tab","L GUI"
"9","5","2","Icon","Key Press","2 and At","L Ctrl"
"9","8","2","Win+Pause","Key Press","Pause","L GUI"
"9","9","2","Ctrl+Shift+L","Key Press","L","L Ctrl+L Shift"
"9","10","2","Hist","Key Press","H","L Ctrl+L Shift"
"9","11","2","Rel","Key Press","K","L Ctrl"
"9","12","2","UndCO","Key Press","U","L Ctrl+L Shift"
"9","1","3","DLoad","Key Press","D","L Ctrl+L Shift"
"9","2","3","Open","Key Press","O","L Ctrl"
"9","3","3","CpLnk","Key Press","C","L Ctrl+L Shift"
"9","4","3","Page Up","Key Press","UpArrow","Page"
"9","5","3","Group","Key Press","G","L Ctrl+L Shift"
"9","7","3","Vault","Key Press","G","L Ctrl"
"9","8","3","rightarrow_combo","Key Press","RightArrow",""
"9","9","3","Ctrl+Down","Key Press","DownArrow","L Ctrl"
"9","3","4","Win+R","Key Press","R","L GUI"
"10","0","0","ShftEnt","Key Press","Return Enter","L Shift"
"10","1","0","SelAll","Key Press","A","L Ctrl"
"10","2","0","Copy","Key Press","C","L Ctrl"
"10","3","0","Cut","Key Press","X","L Ctrl"
"10","4","0","AutoSum","Key Press","Equals and Plus","L Alt"
"10","9","0","yy","Key Press","yy",""
"10","10","0","Ctrl+Shift+M","Key Press","M","L Ctrl+L Shift"
"10","12","0","Win+C","Key Press","C","L GUI"
"10","0","1","ShftTab","Key Press","Tab","L Shift"
"10","1","1","Sel←","Key Press","LeftArrow","L Ctrl+L Shift"
"10","3","1","Sel↑","Key Press","UpArrow","L Ctrl+L Shift"
"10","5","1","InsTime","Key Press","SemiColon and Colon","L Ctrl+L Shift"
"10","8","1","coach_mouse_lock","coach_mouse_lock","",""
"10","9","1","F7","Key Press","F7",""
"10","10","1","SelHome","Key Press","Home","L Ctrl+L Shift"
"10","11","1","Win+B","Key Press","B","L GUI"
"10","12","1","coach_game_lock","coach_game_lock","",""
"10","0","2","Find","Key Press","F","L Ctrl"
"10","1","2","SelCol","Key Press","Spacebar","L Ctrl"
"10","2","2","F4 $Ref","Key Press","F4",""
"10","3","2","Win+H","Key Press","H","L GUI"
"10","4","2","SelEnd","Key Press","End","L Ctrl+L Shift"
"10","7","2","Win+L","Key Press","L","L GUI"
"10","8","2","Paste","Key Press","V","L Ctrl"
"10","9","2","NextSht","Key Press","PageDown","L Ctrl"
"10","10","2","Undo","Key Press","Z","L Ctrl"
"10","11","2","Win+2","Key Press","2 and At","L GUI"
"10","12","2","Win+N","Key Press","N","L GUI"
"10","0","3","F4","Key Press","F4",""
"10","1","3","Replace","Key Press","H","L Ctrl"
"10","2","3","Win+I","Key Press","I","L GUI"
"10","3","3","NumFmt","Key Press","1 and Bang","L Ctrl+L Shift"
"10","4","3","Win+1","Key Press","1 and Bang","L GUI"
"10","5","3","Ctrl+Page Down","Key Press","PageDown","L Ctrl"
"10","7","3","F3","Key Press","F3",""
"10","8","3","Win+E","Key Press","E","L GUI"
"10","10","3","grave accent_combo","Key Press","Grave Accent and Tilde",""
"10","11","3","Win+Left","Key Press","LeftArrow","L GUI"
"10","3","4","Base","coach_base","",""
"10","4","4","f13","Key Press","F13",""
"10","7","4","Win+T","Key Press","T","L GUI"
"10","7","5","Win+Ctrl+D","Key Press","D","L Ctrl+L GUI"`;

function parseExpected() {
  const lines = EXPECTED_CSV.trim().split('\n');
  const headers = lines[0].split(',').map(h => h.split(String.fromCharCode(34)).join('').trim());
  const out = [];
  for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split(',').map(p => p.split(String.fromCharCode(34)).join('').trim());
    const obj = {};
    for (let j = 0; j < headers.length; j++) obj[headers[j]] = parts[j] || '';
    out.push(obj);
  }
  return out;
}

function runVerify() {
  const expected = parseExpected();
  let pass = 0, fail = 0, errors = [];
  for (const exp of expected) {
    const layer = parseInt(exp.layer);
    const x = parseInt(exp.x);
    const y = parseInt(exp.y);
    const actual = getKeyBinding(layer, x, y);
    if (!actual) {
      fail++;
      errors.push({layer, x, y, expected: exp, error: 'key not found'});
      continue;
    }
    const bMatch = actual.behavior.toLowerCase() === exp.behavior.toLowerCase();
    const pMatch = actual.parameter.toLowerCase() === exp.parameter.toLowerCase();
    const mMatch = actual.modifiers === exp.modifiers;
    if (bMatch && pMatch && mMatch) {
      pass++;
    } else {
      fail++;
      errors.push({layer, x, y, expected: exp, actual});
    }
  }
  console.log('Verify result: ' + pass + ' pass, ' + fail + ' fail (' + (pass/(pass+fail)*100).toFixed(1) + '%)');
  window._CHARYBDIS_VERIFY_RESULT = {pass, fail, errors};
}

runVerify();
