// ZMK Studio verify script for evolved V2 layout
window.CHARYBDIS_VERSION = "evolved-v2";

function getKeyBinding(layer, x, y) {
  const btn = document.querySelector(`[data-layer='${layer}'][data-x='${x}'][data-y='${y}']`);
  if (!btn) return null;
  const behavior = btn.querySelector('.behavior-name')?.textContent?.trim() || '';
  const parameter = btn.querySelector('.parameter-name')?.textContent?.trim() || '';
  const modifiers = Array.from(btn.querySelectorAll('.modifier-tag')).map(m => m.textContent.trim()).join('+');
  return {behavior, parameter, modifiers};
}

const EXPECTED_CSV = `"layer","x","y","label","behavior","parameter","modifiers"
"0","0","0","_base_escape","Key Press","_base_escape",""
"0","1","0","_base_1","Key Press","_base_1",""
"0","2","0","_base_2","Key Press","_base_2",""
"0","3","0","_base_3","Key Press","_base_3",""
"0","4","0","_base_4","Key Press","_base_4",""
"0","5","0","_base_5","Key Press","_base_5",""
"0","7","0","_base_6","Key Press","_base_6",""
"0","8","0","_base_7","Key Press","_base_7",""
"0","9","0","_base_8","Key Press","_base_8",""
"0","10","0","_base_9","Key Press","_base_9",""
"0","11","0","_base_0","Key Press","_base_0",""
"0","12","0","_base_delete","Key Press","_base_delete",""
"0","0","1","_base_tab","Key Press","_base_tab",""
"0","1","1","_base_q","Key Press","_base_q",""
"0","2","1","_base_w","Key Press","_base_w",""
"0","3","1","_base_e","Key Press","_base_e",""
"0","4","1","_base_r","Key Press","_base_r",""
"0","5","1","_base_t","Key Press","_base_t",""
"0","7","1","_base_y","Key Press","_base_y",""
"0","8","1","_base_u","Key Press","_base_u",""
"0","9","1","_base_i","Key Press","_base_i",""
"0","10","1","_base_o","Key Press","_base_o",""
"0","11","1","_base_p","Key Press","_base_p",""
"0","12","1","_base_[","Key Press","_base_[",""
"0","0","2","_base_leftshift","Key Press","_base_leftshift",""
"0","1","2","_base_a","Key Press","_base_a",""
"0","2","2","_base_s","Key Press","_base_s",""
"0","3","2","_base_d","Key Press","_base_d",""
"0","4","2","_base_f","Key Press","_base_f",""
"0","5","2","_base_g","Key Press","_base_g",""
"0","7","2","_base_h","Key Press","_base_h",""
"0","8","2","_base_j","Key Press","_base_j",""
"0","9","2","_base_k","Key Press","_base_k",""
"0","10","2","_base_l","Key Press","_base_l",""
"0","11","2","_base_;","Key Press","_base_;",""
"0","12","2","_base_'","Key Press","_base_'",""
"0","0","3","_base_leftcontrol","Key Press","_base_leftcontrol",""
"0","1","3","_base_z","Key Press","_base_z",""
"0","2","3","_base_x","Key Press","_base_x",""
"0","3","3","_base_c","Key Press","_base_c",""
"0","4","3","_base_v","Key Press","_base_v",""
"0","5","3","_base_b","Key Press","_base_b",""
"0","7","3","_base_n","Key Press","_base_n",""
"0","8","3","_base_m","Key Press","_base_m",""
"0","9","3","_base_,","Key Press","_base_,",""
"0","10","3","_base_.","Key Press","_base_.",""
"0","11","3","_base_/","Key Press","_base_/",""
"0","12","3","_base_\","Key Press","_base_\",""
"0","3","4","Nav","coach_l1_hold","",""
"0","4","4","␣","Key Press","Spacebar",""
"0","5","4","Ctrl+Q","Key Press","Q","L Ctrl"
"0","7","4","System","coach_l4_hold","",""
"0","8","4","Window","coach_l3_hold","",""
"0","4","5","Ctrl+R","Key Press","R","L Ctrl"
"0","5","5","Alt+Shift+D","Key Press","D","L Alt+L Shift"
"0","7","5","Ret","Key Press","Return Enter",""
"1","0","0","Win+B","Key Press","B","L GUI"
"1","2","0","F","Key Press","F","L Ctrl"
"1","3","0","Ctrl+1","Key Press","1 and Bang","L Ctrl"
"1","4","0","Win+I","Key Press","I","L GUI"
"1","5","0","F1","Key Press","F1",""
"1","8","0","Ctrl+O","Key Press","O","L Ctrl"
"1","9","0","Win+I","Key Press","I","L GUI"
"1","10","0","Win+K","Key Press","K","L GUI"
"1","11","0","_base_h","Key Press","_base_h",""
"1","0","1","Code","Toggle Layer","Layer::5",""
"1","1","1","Alt+F12","Key Press","F12","L Alt"
"1","2","1","Ctrl+Shift+O","Key Press","O","L Ctrl+L Shift"
"1","3","1","Ctrl+Shift+F6","Key Press","F6","L Ctrl+L Shift"
"1","4","1","F3","Key Press","F3",""
"1","5","1","Ctrl+D","Key Press","D","L Ctrl"
"1","7","1","Shift+Alt+A","Key Press","A","L Shift+L Alt"
"1","8","1","Alt+Click","Key Press","Click","L Alt"
"1","9","1","Win+1","Key Press","1 and Bang","L GUI"
"1","10","1","Win+Right","Key Press","RightArrow","L GUI"
"1","11","1","MB1","Mouse Key Press","MB1",""
"1","0","2","Ctrl+G","Key Press","G","L Ctrl"
"1","1","2","Ctrl+Shift+F","Key Press","F","L Ctrl+L Shift"
"1","2","2","Ctrl+Enter","Key Press","Return Enter","L Ctrl"
"1","3","2","Alt+Left","Key Press","LeftArrow","L Alt"
"1","4","2","F5","Key Press","F5",""
"1","5","2","Ctrl+Tab","Key Press","Tab","L Ctrl"
"1","7","2","Alt+F12","Key Press","F12","L Alt"
"1","8","2","Shift+Alt+Down","Key Press","DownArrow","L Shift+L Alt"
"1","9","2","Win+C","Key Press","C","L GUI"
"1","10","2","F2","Key Press","F2",""
"1","11","2","MB5","Mouse Key Press","MB5",""
"1","12","2","Win+Up","Key Press","UpArrow","L GUI"
"1","0","3","_base_0","Key Press","_base_0",""
"1","2","3","Ctrl+/","Key Press","ForwardSlash and QuestionMark","L Ctrl"
"1","3","3","Ctrl+End","Key Press","End","L Ctrl"
"1","4","3","Ctrl+Up","Key Press","UpArrow","L Ctrl"
"1","5","3","Ctrl+Shift+N","Key Press","N","L Ctrl+L Shift"
"1","7","3","C","Key Press","C","L Ctrl"
"1","8","3","Ctrl+K","Key Press","K","L Ctrl"
"1","9","3","_base_'","Key Press","_base_'",""
"1","11","3","Shift+Alt+Down","Key Press","DownArrow","L Alt+L Shift"
"1","3","4","F4","Key Press","F4",""
"1","4","4","Ctrl+Shift+Up","Key Press","UpArrow","L Ctrl+L Shift"
"1","5","4","Ctrl+Shift+;","Key Press","SemiColon and Colon","L Ctrl+L Shift"
"1","7","4","Ctrl+Shift+2","Key Press","2 and At","L Ctrl+L Shift"
"1","8","4","Ctrl+M","Key Press","M","L Ctrl"
"1","4","5","Ctrl+Shift+6","Key Press","6 and Caret","L Ctrl+L Shift"
"1","5","5","Alt+Shift+-","Key Press","-","L Alt+L Shift"
"1","7","5","_base_7","Key Press","_base_7",""
"2","0","0","Snip","Key Press","PrintScreen","L GUI+L Shift"
"2","1","0","_base_i","Key Press","_base_i",""
"2","2","0","_base_[","Key Press","_base_[",""
"2","3","0","f10","Key Press","F10",""
"2","4","0","Ctrl+Shift+G","Key Press","G","L Ctrl+L Shift"
"2","5","0","_base_9","Key Press","_base_9",""
"2","8","0","Ctrl+2","Key Press","2 and At","L Ctrl"
"2","9","0","Win+P","Key Press","P","L GUI"
"2","10","0","Win+Ctrl+F4","Key Press","F4","L GUI+L Ctrl"
"2","0","1","Win+E","Key Press","E","L GUI"
"2","1","1","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"2","2","1","Shift+Enter","Key Press","Return Enter","L Shift"
"2","3","1","Ctrl+Shift+L","Key Press","L","L Ctrl+L Shift"
"2","4","1","Ctrl+-","Key Press","-","L Ctrl"
"2","5","1","Ctrl+Shift+J","Key Press","J","L Ctrl+L Shift"
"2","7","1","Shift+Tab","Key Press","Tab","L Shift"
"2","8","1","Ctrl+Shift+F5","Key Press","F5","L Ctrl+L Shift"
"2","9","1","Win+Left","Key Press","LeftArrow","L GUI"
"2","10","1","Win+Shift+Right","Key Press","RightArrow","L GUI+L Shift"
"2","11","1","MB2","Mouse Key Press","MB2",""
"2","12","1","_base_5","Key Press","_base_5",""
"2","0","2","MB4","Mouse Key Press","default_transform",""
"2","1","2","Ctrl+U","Key Press","U","L Ctrl"
"2","2","2","Ctrl+C","Key Press","C","L Ctrl"
"2","3","2","Ctrl+3","Key Press","3 and Hash","L Ctrl"
"2","4","2","Ctrl+F5","Key Press","F5","L Ctrl"
"2","5","2","Ctrl+Shift+Tab","Key Press","Tab","L Ctrl+L Shift"
"2","7","2","Ctrl+Shift+`","Key Press","`","L Ctrl+L Shift"
"2","8","2","Ctrl+Alt+Down","Key Press","DownArrow","L Ctrl+L Alt"
"2","9","2","Win+Shift+S","Key Press","S","L GUI+L Shift"
"2","10","2","Win+X","Key Press","X","L GUI"
"2","11","2","MB3","Mouse Key Press","MB3",""
"2","12","2","Scroll","Toggle Layer","Layer::6",""
"2","1","3","_base_.","Key Press","_base_.",""
"2","2","3","_base_f","Key Press","_base_f",""
"2","3","3","Ctrl+Page Up","Key Press","UpArrow","L Ctrl+Page"
"2","4","3","Ctrl+Shift+Home","Key Press","Home","L Ctrl+L Shift"
"2","5","3","Paste","Key Press","V","L Ctrl"
"2","7","3","Shift+Alt+Down","Key Press","DownArrow","L Alt+L Shift"
"2","8","3","_base_/","Key Press","_base_/",""
"2","9","3","_base_delete","Key Press","_base_delete",""
"2","10","3","Undo","Key Press","Z","L Ctrl"
"2","11","3","Speed","Momentary Layer","Layer::8",""
"2","12","3","Ctrl+Shift+Enter","Key Press","Return Enter","L Ctrl+L Shift"
"2","3","4","Ctrl+Space","Key Press","Spacebar","L Ctrl"
"2","4","4","Ctrl+Shift+%","Key Press","%","L Ctrl+L Shift"
"2","5","4","Ctrl+Shift+1","Key Press","1 and Bang","L Ctrl+L Shift"
"2","7","4","forwardslash_combo","Key Press","ForwardSlash and QuestionMark",""
"2","8","4","left brace_combo","Key Press","Left Brace",""
"2","4","5","Ctrl+[","Key Press","Left Brace","L Ctrl"
"2","7","5","right brace_combo","Key Press","Right Brace",""
"3","2","0","equal","Key Press","Equals and Plus",""
"3","3","0","_base_n","Key Press","_base_n",""
"3","4","0","QSett","Key Press","A","L GUI"
"3","5","0","Notif","Key Press","N","L GUI"
"3","7","0","TskCy","Key Press","T","L GUI"
"3","9","0","Win+A","Key Press","A","L GUI"
"3","10","0","Win+M","Key Press","M","L GUI"
"3","11","0","left bracket_combo","Key Press","9 and Left Bracket",""
"3","0","1","BT1","Bluetooth","BT_SEL 1",""
"3","1","1","f17","Key Press","F17",""
"3","2","1","Ctrl+B","Key Press","B","L Ctrl"
"3","3","1","Ctrl+6","Key Press","6 and Caret","L Ctrl"
"3","4","1","Ctrl+P","Key Press","P","L Ctrl"
"3","5","1","Ctrl+Shift+I","Key Press","I","L Ctrl+L Shift"
"3","7","1","Ctrl+,","Key Press","Comma and LessThan","L Ctrl"
"3","8","1","F9","Key Press","F9",""
"3","9","1","Alt+Tab","Key Press","Tab","L Alt"
"3","10","1","Win+3","Key Press","3 and Hash","L GUI"
"3","11","1","ScrollDown","Key Press","ScrollDown",""
"3","12","1","Shift+F8","Key Press","F8","L Shift"
"3","0","2","Ctrl+U","Key Press","U","L Ctrl"
"3","1","2","Ctrl+Shift+D","Key Press","D","L Ctrl+L Shift"
"3","2","2","Ctrl+V","Key Press","V","L Ctrl"
"3","3","2","Ctrl+2","Key Press","2 and At","L Ctrl"
"3","4","2","Ctrl+Shift+C","Key Press","C","L Ctrl+L Shift"
"3","5","2","Ctrl+W","Key Press","W","L Ctrl"
"3","7","2","Ctrl+Shift+Z","Key Press","Z","L Ctrl+L Shift"
"3","8","2","Ctrl+Alt+Up","Key Press","UpArrow","L Ctrl+L Alt"
"3","9","2","Alt+F4","Key Press","F4","L Alt"
"3","10","2","Win+Space","Key Press","Spacebar","L GUI"
"3","11","2","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"3","12","2","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"3","0","3","Ctrl+O","Key Press","O","L Ctrl"
"3","3","3","Ctrl+Left","Key Press","LeftArrow","L Ctrl"
"3","4","3","Ctrl+;","Key Press","SemiColon and Colon","L Ctrl"
"3","5","3","Ctrl+8","Key Press","8 and Star","L Ctrl"
"3","7","3","Tab","Key Press","Tab","L Alt"
"3","8","3","Ctrl+Y","Key Press","Y","L Ctrl"
"3","9","3","BT3","Bluetooth","BT_SEL 3",""
"3","10","3","_base_\","Key Press","_base_\",""
"3","11","3","Ctrl+Tab","Key Press","Tab","L Ctrl"
"3","12","3","Ctrl+Shift+N","Key Press","N","L Ctrl+L Shift"
"3","3","4","Alt+=","Key Press","=","L Alt"
"3","4","4","Ctrl+Shift+Down","Key Press","DownArrow","L Ctrl+L Shift"
"3","5","4","Ctrl+Shift+<","Key Press","<","L Ctrl+L Shift"
"3","7","4","Shift+Delete","Key Press","Dash and Underscore","L Shift"
"3","4","5","Ctrl+Shift+>","Key Press",">","L Ctrl+L Shift"
"3","5","5","Alt+Shift++","Key Press","Shift","L Alt"
"4","0","0","BT0","Bluetooth","BT_SEL 0",""
"4","1","0","BT1","Bluetooth","BT_SEL 1",""
"4","2","0","BT2","Bluetooth","BT_SEL 2",""
"4","3","0","BT3","Bluetooth","BT_SEL 3",""
"4","4","0","BT4","Bluetooth","BT_SEL 4",""
"4","5","0","_base_k","Key Press","_base_k",""
"4","7","0","Ctrl+Shift+X","Key Press","X","L Ctrl+L Shift"
"4","8","0","f6","Key Press","F6",""
"4","9","0","Win+T","Key Press","T","L GUI"
"4","10","0","Win+B","Key Press","B","L GUI"
"4","11","0","Ctrl+Enter","Key Press","Return Enter","L Ctrl"
"4","12","0","Bootloader","Bootloader","",""
"4","0","1","Ctrl+G","Key Press","G","L Ctrl"
"4","1","1","Ctrl+O","Key Press","O","L Ctrl"
"4","2","1","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"4","3","1","Ctrl+F","Key Press","F","L Ctrl"
"4","4","1","gg","Key Press","gg",""
"4","5","1","gi","Key Press","gi",""
"4","7","1","Ctrl+]","Key Press","]","L Ctrl"
"4","8","1","Shift+F11","Key Press","F11","L Shift"
"4","9","1","Win+S","Key Press","S","L GUI"
"4","10","1","Win+V","Key Press","V","L GUI"
"4","11","1","ScrollUp","Key Press","ScrollUp",""
"4","12","1","_base_leftshift","Key Press","_base_leftshift",""
"4","0","2","Backspace","Key Press","Delete",""
"4","1","2","Ctrl+A","Key Press","A","L Ctrl"
"4","2","2","Ctrl+Shift+M","Key Press","M","L Ctrl+L Shift"
"4","3","2","Ctrl+E","Key Press","E","L Ctrl"
"4","4","2","Ctrl+L","Key Press","L","L Ctrl"
"4","5","2","Ctrl+T","Key Press","T","L Ctrl"
"4","7","2","Alt+Up","Key Press","UpArrow","L Alt"
"4","8","2","Ctrl+`","Key Press","`","L Ctrl"
"4","9","2","Win+H","Key Press","H","L GUI"
"4","10","2","Win+E","Key Press","E","L GUI"
"4","11","2","f5","Key Press","F5",""
"4","12","2","RightArrow","Key Press","RightArrow",""
"4","0","3","Excel","Toggle Layer","Layer::10",""
"4","1","3","Shift+Alt+Up","Key Press","UpArrow","L Alt+L Shift"
"4","2","3","Ctrl+F6","Key Press","F6","L Ctrl"
"4","3","3","Ctrl+Home","Key Press","Home","L Ctrl"
"4","4","3","Ctrl+Page Down","Key Press","DownArrow","L Ctrl+Page"
"4","5","3","F22","Key Press","F22",""
"4","7","3","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"4","8","3","home","Key Press","Home",""
"4","9","3","f11","Key Press","F11",""
"4","10","3","f7","Key Press","F7",""
"4","11","3","_base_y","Key Press","_base_y",""
"4","12","3","Accept","Key Press","A","L Ctrl+L Shift"
"4","3","4","Ctrl+Shift++","Key Press","Shift","L Ctrl"
"4","4","4","Ctrl+Shift+Right","Key Press","RightArrow","L Ctrl+L Shift"
"4","5","4","Shift+Click","Key Press","Click","L Shift"
"4","7","4","Alt+P","Key Press","P","L Alt"
"4","8","4","UpArrow","Key Press","UpArrow",""
"4","4","5","Ctrl+Shift+Q","Key Press","Q","L Ctrl+L Shift"
"4","5","5","Down","Key Press","DownArrow",""
"5","2","0","_base_6","Key Press","_base_6",""
"5","4","0","GoSym","Key Press","O","L Ctrl+L Shift"
"5","7","0","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"5","8","0","_base_spacebar","Key Press","_base_spacebar",""
"5","9","0","Win+Ctrl+D","Key Press","D","L Ctrl+L GUI"
"5","10","0","Explr","Key Press","E","L Ctrl+L Shift"
"5","0","1","Wrap","Key Press","Z","L Alt"
"5","1","1","_base_;","Key Press","_base_;",""
"5","2","1","Ctrl+Z","Key Press","Z","L Ctrl"
"5","3","1","Ctrl+Shift+X","Key Press","X","L Ctrl+L Shift"
"5","4","1","Ctrl+Shift+G","Key Press","G","L Ctrl+L Shift"
"5","5","1","Ctrl+H","Key Press","H","L Ctrl"
"5","7","1","Ctrl+\","Key Press","Backslash and Pipe","L Ctrl"
"5","8","1","Ctrl+K S","Key Press","S","L Ctrl+K"
"5","9","1","Ctrl+X","Key Press","X","L Ctrl"
"5","10","1","Win+D","Key Press","D","L GUI"
"5","11","1","backslash","Key Press","Backslash and Pipe",""
"5","0","2","Ctrl+N","Key Press","N","L Ctrl"
"5","1","2","Save","Key Press","S","L Ctrl"
"5","2","2","Ctrl+4","Key Press","4 and Dollar","L Ctrl"
"5","3","2","Ctrl+5","Key Press","5 and Percent","L Ctrl"
"5","4","2","Shift+Space","Key Press","Spacebar","L Shift"
"5","5","2","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"5","7","2","Shift+Alt+Right","Key Press","RightArrow","L Shift+L Alt"
"5","8","2","Ctrl+O","Key Press","O","L Ctrl"
"5","9","2","Win+R","Key Press","R","L GUI"
"5","10","2","Ctrl+Y","Key Press","Y","L Ctrl"
"5","11","2","coach_travel_toggle","coach_travel_toggle","",""
"5","1","3","PstNF","Key Press","V","L Ctrl+L Shift"
"5","3","3","Alt+Shift+Down","Key Press","DownArrow","L Alt+L Shift"
"5","4","3","Ext","Key Press","X","L Ctrl+L Shift"
"5","5","3","f8","Key Press","F8",""
"5","10","3","keypad 3","Key Press","3 and PageDn",""
"5","12","3","_base_a","Key Press","_base_a",""
"5","3","4","Ctrl+Shift+9","Key Press","9 and Left Bracket","L Ctrl+L Shift"
"5","4","4","Ctrl+Shift+End","Key Press","End","L Ctrl+L Shift"
"5","5","5","_base_1","Key Press","_base_1",""
"6","2","0","_base_p","Key Press","_base_p",""
"6","3","0","Alt+=","Key Press","Equals and Plus","L Alt"
"6","4","0","Ctrl+Left","Key Press","LeftArrow","L Ctrl"
"6","7","0","_base_2","Key Press","_base_2",""
"6","8","0","Ctrl+Q","Key Press","Q","L Ctrl"
"6","9","0","Win+Pause","Key Press","Pause","L GUI"
"6","12","0","_base_d","Key Press","_base_d",""
"6","2","1","Ctrl+I","Key Press","I","L Ctrl"
"6","3","1","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"6","4","1","F11","Key Press","F11",""
"6","5","1","Ctrl++","Key Press","LeftControl",""
"6","7","1","Ctrl+[","Key Press","[","L Ctrl"
"6","8","1","Shift+F3","Key Press","F3","L Shift"
"6","9","1","Win+Shift+Left","Key Press","LeftArrow","L GUI+L Shift"
"6","10","1","Win+Up","Key Press","UpArrow","L GUI"
"6","11","1","MB4","Mouse Key Press","MB4",""
"6","1","2","Ctrl+Shift+R","Key Press","R","L Ctrl+L Shift"
"6","2","2","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"6","3","2","Ctrl+1","Key Press","1 and Bang","L Ctrl"
"6","4","2","Ctrl+0","Key Press","0 and Right Bracket","L Ctrl"
"6","5","2","F12","Key Press","F12",""
"6","7","2","F8","Key Press","F8",""
"6","8","2","F10","Key Press","F10",""
"6","9","2","Win+Down","Key Press","DownArrow","L GUI"
"6","10","2","Win+Ctrl+Left","Key Press","LeftArrow","L GUI+L Ctrl"
"6","11","2","Ctrl+Shift+Up","Key Press","UpArrow","L Ctrl+L Shift"
"6","0","3","_base_tab","Key Press","_base_tab",""
"6","2","3","Ctrl+Shift++","Key Press","Equals and Plus","L Ctrl+L Shift"
"6","3","3","F7","Key Press","F7",""
"6","4","3","Win+Shift+Right","Key Press","RightArrow","L GUI+L Shift"
"6","5","3","Ctrl+7","Key Press","7 and Ampersand","L Ctrl"
"6","7","3","Ctrl+Shift+I","Key Press","I","L Ctrl+L Shift"
"6","8","3","Ctrl+Shift+T","Key Press","T","L Ctrl+L Shift"
"6","9","3","Ctrl+6","Key Press","6 and Caret","L Ctrl"
"6","10","3","Ctrl+Shift+Right","Key Press","RightArrow","L Ctrl+L Shift"
"6","3","4","Ctrl+Shift+!","Key Press","!","L Ctrl+L Shift"
"6","4","4","Ctrl+Click","Key Press","Click","L Ctrl"
"6","7","5","_base_w","Key Press","_base_w",""
"7","1","1","_base_9","Key Press","_base_9",""
"7","2","1","UpArrow","Key Press","UpArrow",""
"7","3","1","_base_3","Key Press","_base_3",""
"7","9","1","_base_3","Key Press","_base_3",""
"7","10","1","UpArrow","Key Press","UpArrow",""
"7","11","1","_base_9","Key Press","_base_9",""
"7","1","2","LeftArrow","Key Press","LeftArrow",""
"7","2","2","DownArrow","Key Press","DownArrow",""
"7","3","2","RightArrow","Key Press","RightArrow",""
"7","4","2","_base_z","Key Press","_base_z",""
"7","8","2","_base_z","Key Press","_base_z",""
"7","9","2","LeftArrow","Key Press","LeftArrow",""
"7","10","2","DownArrow","Key Press","DownArrow",""
"7","11","2","RightArrow","Key Press","RightArrow",""
"7","1","3","_base_x","Key Press","_base_x",""
"7","2","3","_base_c","Key Press","_base_c",""
"7","3","3","_base_leftshift","Key Press","_base_leftshift",""
"7","4","3","_base_escape","Key Press","_base_escape",""
"7","8","3","_base_escape","Key Press","_base_escape",""
"7","9","3","_base_leftshift","Key Press","_base_leftshift",""
"7","10","3","_base_c","Key Press","_base_c",""
"7","11","3","_base_x","Key Press","_base_x",""
"7","3","4","Exit Base","coach_base","",""
"7","4","4","_base_spacebar","Key Press","_base_spacebar",""
"7","5","4","Exit Base","coach_base","",""
"7","7","4","Exit Base","coach_base","",""
"7","8","4","Exit Base","coach_base","",""
"7","4","5","Click","Mouse Key Press","default_transform",""
"7","5","5","Right Click","Mouse Key Press","default_transform",""
"7","7","5","_base_returnenter","Key Press","_base_returnenter",""
"8","0","0","_base_b","Key Press","_base_b",""
"8","2","0","_base_q","Key Press","_base_q",""
"8","3","0","_base_x","Key Press","_base_x",""
"8","4","0","escape","Key Press","Escape",""
"8","8","0","Shift+Space","Key Press","Spacebar","L Shift"
"8","9","0","Win+Home","Key Press","Home","L GUI"
"8","2","1","Ctrl+K","Key Press","K","L Ctrl"
"8","3","1","Alt+Right","Key Press","RightArrow","L Alt"
"8","4","1","Ctrl+Shift+Del","Key Press","Del","L Ctrl+L Shift"
"8","5","1","Ctrl+S","Key Press","S","L Ctrl"
"8","7","1","Ctrl+K Ctrl+F","Key Press","F","L Ctrl+K+L Ctrl"
"8","8","1","Shift+Alt+Up","Key Press","UpArrow","L Shift+L Alt"
"8","9","1","Win+Tab","Key Press","Tab","L GUI"
"8","10","1","Win+2","Key Press","2 and At","L GUI"
"8","11","1","DownArrow","Key Press","DownArrow",""
"8","1","2","Ctrl+Shift+U","Key Press","U","L Ctrl+L Shift"
"8","2","2","Up","Key Press","UpArrow",""
"8","3","2","Ctrl+Right","Key Press","RightArrow","L Ctrl"
"8","4","2","Page Up","Key Press","UpArrow","Page"
"8","5","2","Ctrl+Shift+T","Key Press","T","L Ctrl+L Shift"
"8","7","2","Shift+Alt+Left","Key Press","LeftArrow","L Shift+L Alt"
"8","8","2","Alt+Down","Key Press","DownArrow","L Alt"
"8","9","2","Win+L","Key Press","L","L GUI"
"8","10","2","Win+4","Key Press","4 and Dollar","L GUI"
"8","11","2","LeftArrow","Key Press","LeftArrow",""
"8","1","3","_base_returnenter","Key Press","_base_returnenter",""
"8","3","3","Page Down","Key Press","DownArrow","Page"
"8","4","3","Alt+Shift+Up","Key Press","UpArrow","L Alt+L Shift"
"8","5","3","Win+.","Key Press","Period and GreaterThan","L GUI"
"8","7","3","Win+;","Key Press","SemiColon and Colon","L GUI"
"8","8","3","Alt+Up","Key Press","UpArrow","L Alt"
"8","9","3","Ctrl+Home","Key Press","Home","L Ctrl"
"8","3","4","Ctrl+Shift+Left","Key Press","LeftArrow","L Ctrl+L Shift"
"8","4","4","Ctrl+Shift+$","Key Press","$","L Ctrl+L Shift"
"8","7","4","Exit Travel","coach_travel_off","",""
"8","4","5","Delete","Key Press","Delete",""
"8","5","5","F10","Key Press","F10",""
"9","4","0","_base_j","Key Press","_base_j",""
"9","8","0","Ctrl+Up","Key Press","UpArrow","L Ctrl"
"9","9","0","_base_4","Key Press","_base_4",""
"9","11","0","_base_o","Key Press","_base_o",""
"9","0","1","_base_r","Key Press","_base_r",""
"9","1","1","WfSt","Key Press","W","L Ctrl+L Shift"
"9","2","1","Ctrl+Shift+P","Key Press","P","L Ctrl+L Shift"
"9","3","1","Ctrl+Shift+B","Key Press","B","L Ctrl+L Shift"
"9","4","1","_base_3","Key Press","_base_3",""
"9","5","1","Ctrl+9","Key Press","9 and Left Bracket","L Ctrl"
"9","7","1","Print","Key Press","P","L Ctrl"
"9","8","1","Ctrl+K Ctrl+W","Key Press","W","L Ctrl+K+L Ctrl"
"9","9","1","Win+5","Key Press","5 and Percent","L GUI"
"9","10","1","Win+Ctrl+Right","Key Press","RightArrow","L GUI+L Ctrl"
"9","11","1","_base_s","Key Press","_base_s",""
"9","12","1","_base_g","Key Press","_base_g",""
"9","0","2","_base_m","Key Press","_base_m",""
"9","1","2","Save","Key Press","S","L Ctrl"
"9","2","2","Ctrl+N","Key Press","N","L Ctrl"
"9","3","2","Ctrl+Down","Key Press","DownArrow","L Ctrl"
"9","4","2","Alt+D","Key Press","D","L Alt"
"9","5","2","yy","Key Press","yy",""
"9","7","2","Shift+F8","Key Press","F8","L Shift"
"9","8","2","Ctrl+Shift+\","Key Press","Backslash and Pipe","L Ctrl+L Shift"
"9","9","2","Win+;","Key Press","SemiColon and Colon","L GUI"
"9","10","2","Win+.","Key Press","Period and GreaterThan","L GUI"
"9","11","2","_base_v","Key Press","_base_v",""
"9","12","2","UndCO","Key Press","U","L Ctrl+L Shift"
"9","1","3","_base_l","Key Press","_base_l",""
"9","2","3","Open","Key Press","O","L Ctrl"
"9","3","3","CpLnk","Key Press","C","L Ctrl+L Shift"
"9","4","3","Notif","Key Press","F5","L Ctrl+L Shift"
"9","5","3","_base_u","Key Press","_base_u",""
"9","7","3","Vault","Key Press","G","L Ctrl"
"9","8","3","rightarrow_combo","Key Press","RightArrow",""
"9","9","3","Ctrl+Down","Key Press","DownArrow","L Ctrl"
"9","3","4","_base_,","Key Press","_base_,",""
"10","0","0","ShftEnt","Key Press","Return Enter","L Shift"
"10","1","0","SelAll","Key Press","A","L Ctrl"
"10","2","0","Copy","Key Press","C","L Ctrl"
"10","3","0","Cut","Key Press","X","L Ctrl"
"10","4","0","AutoSum","Key Press","Equals and Plus","L Alt"
"10","7","0","_base_e","Key Press","_base_e",""
"10","10","0","_base_z","Key Press","_base_z",""
"10","11","0","_base_8","Key Press","_base_8",""
"10","12","0","Win+C","Key Press","C","L GUI"
"10","0","1","ShftTab","Key Press","Tab","L Shift"
"10","1","1","Sel←","Key Press","LeftArrow","L Ctrl+L Shift"
"10","2","1","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"10","3","1","Ctrl+G","Key Press","G","L Ctrl"
"10","4","1","Ctrl+J","Key Press","J","L Ctrl"
"10","5","1","?","Key Press","?",""
"10","8","1","Ctrl+K Ctrl+S","Key Press","S","L Ctrl+K+L Ctrl"
"10","9","1","Ctrl+Shift+Esc","Key Press","Escape","L Ctrl+L Shift"
"10","10","1","Win+Ctrl+D","Key Press","D","L GUI+L Ctrl"
"10","11","1","_base_t","Key Press","_base_t",""
"10","12","1","_base_leftcontrol","Key Press","_base_leftcontrol",""
"10","0","2","Find","Key Press","F","L Ctrl"
"10","1","2","SelCol","Key Press","Spacebar","L Ctrl"
"10","2","2","Ctrl+Shift+A","Key Press","A","L Ctrl+L Shift"
"10","3","2","Ctrl+.","Key Press","Period and GreaterThan","L Ctrl"
"10","4","2","Alt+Home","Key Press","Home","L Alt"
"10","5","2","Alt+F","Key Press","F","L Alt"
"10","7","2","Ctrl+Shift+Enter","Key Press","Return Enter","L Ctrl+L Shift"
"10","8","2","Shift+F5","Key Press","F5","L Shift"
"10","9","2","Alt+Shift","Key Press","Shift","L Alt"
"10","10","2","Win+N","Key Press","N","L GUI"
"10","11","2","Win+2","Key Press","2 and At","L GUI"
"10","12","2","Win+N","Key Press","N","L GUI"
"10","0","3","HideRow","Key Press","9 and Left Bracket","L Ctrl"
"10","1","3","Replace","Key Press","H","L Ctrl"
"10","2","3","Delete","Key Press","Dash and Underscore","L Ctrl"
"10","3","3","NumFmt","Key Press","1 and Bang","L Ctrl+L Shift"
"10","4","3","Ctrl+Alt+Up","Key Press","UpArrow","L Alt+L Ctrl"
"10","5","3","Ctrl+Page Down","Key Press","PageDown","L Ctrl"
"10","8","3","Win+E","Key Press","E","L GUI"
"10","10","3","grave accent_combo","Key Press","Grave Accent and Tilde",""
"10","11","3","Win+Left","Key Press","LeftArrow","L GUI"
"10","3","4","Base","coach_base","",""
"10","4","4","Ctrl+Shift+~","Key Press","~","L Ctrl+L Shift"
"10","7","4","Win+T","Key Press","T","L GUI"
"10","5","5","_base_c","Key Press","_base_c",""
"10","7","5","Win+Ctrl+D","Key Press","D","L Ctrl+L GUI"`;

function parseExpected() {
  const lines = EXPECTED_CSV.trim().split('\n');
  const headers = lines[0].split(',').map(h => h.split(String.fromCharCode(34)).join('').trim());
  const out = [];
  for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split(',').map(p => p.split(String.fromCharCode(34)).join('').trim());
    const obj = {};
    for (let j = 0; j < headers.length; j++) obj[headers[j]] = parts[j] || '';
    out.push(obj);
  }
  return out;
}

function runVerify() {
  const expected = parseExpected();
  let pass = 0, fail = 0, errors = [];
  for (const exp of expected) {
    const layer = parseInt(exp.layer);
    const x = parseInt(exp.x);
    const y = parseInt(exp.y);
    const actual = getKeyBinding(layer, x, y);
    if (!actual) {
      fail++;
      errors.push({layer, x, y, expected: exp, error: 'key not found'});
      continue;
    }
    const bMatch = actual.behavior.toLowerCase() === exp.behavior.toLowerCase();
    const pMatch = actual.parameter.toLowerCase() === exp.parameter.toLowerCase();
    const mMatch = actual.modifiers === exp.modifiers;
    if (bMatch && pMatch && mMatch) {
      pass++;
    } else {
      fail++;
      errors.push({layer, x, y, expected: exp, actual});
    }
  }
  console.log('Verify result: ' + pass + ' pass, ' + fail + ' fail (' + (pass/(pass+fail)*100).toFixed(1) + '%)');
  window._CHARYBDIS_VERIFY_RESULT = {pass, fail, errors};
}

runVerify();
