// ZMK Studio verify script for evolved V2 layout
window.CHARYBDIS_VERSION = "evolved-v2";

function getKeyBinding(layer, x, y) {
  const btn = document.querySelector(`[data-layer='${layer}'][data-x='${x}'][data-y='${y}']`);
  if (!btn) return null;
  const behavior = btn.querySelector('.behavior-name')?.textContent?.trim() || '';
  const parameter = btn.querySelector('.parameter-name')?.textContent?.trim() || '';
  const modifiers = Array.from(btn.querySelectorAll('.modifier-tag')).map(m => m.textContent.trim()).join('+');
  return {behavior, parameter, modifiers};
}

const EXPECTED_CSV = `"layer","x","y","label","behavior","parameter","modifiers"
"0","0","0","Esc","Key Press","Escape",""
"0","1","0","1","Key Press","1 and Bang",""
"0","2","0","2","Key Press","2 and At",""
"0","3","0","3","Key Press","3 and Hash",""
"0","4","0","4","Key Press","4 and Dollar",""
"0","5","0","5","Key Press","5 and Percent",""
"0","7","0","6","Key Press","6 and Caret",""
"0","8","0","7","Key Press","7 and Ampersand",""
"0","9","0","8","Key Press","8 and Star",""
"0","10","0","9","Key Press","9 and Left Bracket",""
"0","11","0","0","Key Press","0 and Right Bracket",""
"0","12","0","BkSp","Key Press","Delete",""
"0","0","1","Tab","Key Press","Tab",""
"0","1","1","Q","Key Press","Q",""
"0","2","1","W","Key Press","W",""
"0","3","1","E","Key Press","E",""
"0","4","1","R","Key Press","R",""
"0","5","1","T","Key Press","T",""
"0","7","1","Y","Key Press","Y",""
"0","8","1","U","Key Press","U",""
"0","9","1","I","Key Press","I",""
"0","10","1","O","Key Press","O",""
"0","11","1","P","Key Press","P",""
"0","12","1","å","Key Press","Left Brace",""
"0","0","2","Shft","Key Press","LeftShift",""
"0","1","2","A","Key Press","A",""
"0","2","2","S","Key Press","S",""
"0","3","2","D","Key Press","D",""
"0","4","2","F","Key Press","F",""
"0","5","2","G","Key Press","G",""
"0","7","2","H","Key Press","H",""
"0","8","2","J","Key Press","J",""
"0","9","2","K","Key Press","K",""
"0","10","2","L","Key Press","L",""
"0","11","2","ø","Key Press","SemiColon and Colon",""
"0","12","2","æ","Key Press","Left Apos and Double",""
"0","0","3","Ctrl","Key Press","LeftControl",""
"0","1","3","Z","Key Press","Z",""
"0","2","3","X","Key Press","X",""
"0","3","3","C","Key Press","C",""
"0","4","3","V","Key Press","V",""
"0","5","3","B","Key Press","B",""
"0","7","3","N","Key Press","N",""
"0","8","3","M","Key Press","M",""
"0","9","3",",","Key Press","Comma and LessThan",""
"0","10","3",".","Key Press","Period and GreaterThan",""
"0","11","3","/","Key Press","ForwardSlash and QuestionMark",""
"0","12","3","\","Key Press","Backslash and Pipe",""
"0","3","4","Nav","coach_l1_hold","",""
"0","4","4","␣","Key Press","Spacebar",""
"0","5","4","Ctrl+0","Key Press","0 and Right Bracket","L Ctrl"
"0","7","4","System","coach_l4_hold","",""
"0","8","4","Window","coach_l3_hold","",""
"0","4","5","Speed","coach_travel_toggle","",""
"0","5","5","Mouse","coach_l2_hold","",""
"0","7","5","Ret","Key Press","Return Enter",""
"1","0","0","Ctrl+Click","Mouse Key Press","MB1","L Ctrl"
"1","2","0","Ctrl+F","Key Press","F","L Ctrl"
"1","3","0","Ctrl+1","Key Press","1 and Bang","L Ctrl"
"1","4","0","Win+I","Key Press","I","L GUI"
"1","5","0","Ctrl+Shift+G","Key Press","G","L Ctrl+L Shift"
"1","8","0","Ctrl+O","Key Press","O","L Ctrl"
"1","9","0","Ctrl+Shift+C","Key Press","C","L Ctrl+L Shift"
"1","0","1","Up","Key Press","UpArrow",""
"1","1","1","Ctrl+2","Key Press","2 and At","L Ctrl"
"1","2","1","F3","Key Press","F3",""
"1","3","1","Ctrl+Shift+W","Key Press","W","L Ctrl+L Shift"
"1","5","1","Ctrl+V","Key Press","V","L Ctrl"
"1","7","1","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"1","8","1","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"1","10","1","Ctrl+Shift+C","Key Press","C","L Ctrl+L Shift"
"1","11","1","Win+Ctrl+F4","Key Press","F4","L GUI+L Ctrl"
"1","0","2","Ctrl+G","Key Press","G","L Ctrl"
"1","2","2","Ctrl+Shift+U","Key Press","U","L Ctrl+L Shift"
"1","3","2","Win+X","Key Press","X","L GUI"
"1","5","2","F2","Key Press","F2",""
"1","10","2","Ctrl+Shift+F","Key Press","F","L Ctrl+L Shift"
"1","11","2","Ctrl+Home","Key Press","Home","L Ctrl"
"1","12","2","Alt+Down","Key Press","DownArrow","L Alt"
"1","0","3","Ctrl+G","Key Press","G","L Ctrl"
"1","1","3","F2","Key Press","F2",""
"1","2","3","F5","Key Press","F5",""
"1","5","3","Ctrl+Shift+A","Key Press","A","L Ctrl+L Shift"
"1","7","3","Shift+Alt+Right","Key Press","RightArrow","L Shift+L Alt"
"1","9","3","F4","Key Press","F4",""
"1","12","3","Ctrl+O","Key Press","O","L Ctrl"
"1","3","4","Win+N","Key Press","N","L GUI"
"1","4","4","Ctrl+2","Key Press","2 and At","L Ctrl"
"1","5","4","Ctrl+Enter","Key Press","Return Enter","L Ctrl"
"1","7","4","Scroll","Toggle Layer","Layer::6",""
"1","8","4","F5","Key Press","F5",""
"1","4","5","Shift+Alt+Down","Key Press","DownArrow","L Shift+L Alt"
"1","5","5","Shift+Tab","Key Press","Tab","L Shift"
"1","7","5","Base","coach_base","",""
"2","1","0","F9","Key Press","F9",""
"2","3","0","F10","Key Press","F10",""
"2","4","0","Ctrl+Shift+G","Key Press","G","L Ctrl+L Shift"
"2","8","0","Alt+F12","Key Press","F12","L Alt"
"2","10","0","Ctrl+F","Key Press","F","L Ctrl"
"2","1","1","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"2","2","1","Ctrl+W","Key Press","W","L Ctrl"
"2","3","1","F5","Key Press","F5",""
"2","4","1","F5","Key Press","F5",""
"2","8","1","Win+D","Key Press","D","L GUI"
"2","9","1","Win+Space","Key Press","Spacebar","L GUI"
"2","12","1","Ctrl+X","Key Press","X","L Ctrl"
"2","0","2","Ctrl+Alt+Up","Key Press","UpArrow","L Ctrl+L Alt"
"2","1","2","Ctrl+H","Key Press","H","L Ctrl"
"2","2","2","Ctrl+Alt+Down","Key Press","DownArrow","L Ctrl+L Alt"
"2","3","2","Ctrl+Right","Key Press","RightArrow","L Ctrl"
"2","4","2","Ctrl+I","Key Press","I","L Ctrl"
"2","5","2","Ctrl+6","Key Press","6 and Caret","L Ctrl"
"2","7","2","Ctrl+C","Key Press","C","L Ctrl"
"2","8","2","F4","Key Press","F4",""
"2","9","2","coach_travel_toggle","coach_travel_toggle","",""
"2","10","2","coach_base","coach_base","",""
"2","11","2","Ctrl+P","Key Press","P","L Ctrl"
"2","1","3","Ctrl+Shift+\","Key Press","Backslash and Pipe","L Ctrl+L Shift"
"2","2","3","Alt+Left","Key Press","LeftArrow","L Alt"
"2","3","3","Ctrl+G","Key Press","G","L Ctrl"
"2","4","3","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"2","5","3","Ctrl+V","Key Press","V","L Ctrl"
"2","10","3","Ctrl+Z","Key Press","Z","L Ctrl"
"2","11","3","MB5","Mouse Key Press","MB5",""
"2","3","4","Ctrl+Shift+M","Key Press","M","L Ctrl+L Shift"
"2","4","4","coach_travel_toggle","coach_travel_toggle","",""
"2","7","4","coach_mouse_lock","coach_mouse_lock","",""
"2","8","4","Win+E","Key Press","E","L GUI"
"2","4","5","Ctrl+Left","Key Press","LeftArrow","L Ctrl"
"2","5","5","Win+3","Key Press","3 and Hash","L GUI"
"2","7","5","Base","coach_base","",""
"3","4","0","Win+A","Key Press","A","L GUI"
"3","5","0","Win+N","Key Press","N","L GUI"
"3","7","0","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"3","9","0","Ctrl+P","Key Press","P","L Ctrl"
"3","3","1","Win+C","Key Press","C","L GUI"
"3","4","1","Ctrl+R","Key Press","R","L Ctrl"
"3","5","1","Alt+Tab","Key Press","Tab","L Alt"
"3","8","1","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"3","9","1","Ctrl+L","Key Press","L","L Ctrl"
"3","11","1","Ctrl+U","Key Press","U","L Ctrl"
"3","12","1","Shift+F8","Key Press","F8","L Shift"
"3","0","2","Ctrl+U","Key Press","U","L Ctrl"
"3","1","2","Alt+Right","Key Press","RightArrow","L Alt"
"3","2","2","Ctrl+G","Key Press","G","L Ctrl"
"3","3","2","Win+1","Key Press","1 and Bang","L GUI"
"3","4","2","Win+4","Key Press","4 and Dollar","L GUI"
"3","5","2","Win+5","Key Press","5 and Percent","L GUI"
"3","7","2","Win+S","Key Press","S","L GUI"
"3","8","2","Ctrl+Shift+P","Key Press","P","L Ctrl+L Shift"
"3","9","2","Ctrl+Shift+L","Key Press","L","L Ctrl+L Shift"
"3","11","2","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"3","12","2","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"3","0","3","Ctrl+Shift+F6","Key Press","F6","L Ctrl+L Shift"
"3","1","3","Ctrl+F6","Key Press","F6","L Ctrl"
"3","3","3","Win+H","Key Press","H","L GUI"
"3","4","3","Win+Shift+S","Key Press","S","L GUI+L Shift"
"3","5","3","Win+S","Key Press","S","L GUI"
"3","8","3","Alt+Enter","Key Press","Return Enter","L Alt"
"3","9","3","Ctrl+9","Key Press","9 and Left Bracket","L Ctrl"
"3","10","3","Ctrl+H","Key Press","H","L Ctrl"
"3","11","3","Ctrl+K","Key Press","K","L Ctrl"
"3","12","3","Ctrl+Shift+N","Key Press","N","L Ctrl+L Shift"
"3","4","4","Win+B","Key Press","B","L GUI"
"3","5","4","coach_game_lock","coach_game_lock","",""
"3","7","4","Ctrl+Tab","Key Press","Tab","L Ctrl"
"3","8","4","Ctrl+`","Key Press","Grave Accent and Tilde","L Ctrl"
"3","4","5","Win+Ctrl+Left","Key Press","LeftArrow","L GUI+L Ctrl"
"3","5","5","Win+Ctrl+Right","Key Press","RightArrow","L GUI+L Ctrl"
"3","7","5","Scroll","Momentary Layer","Layer::6",""
"4","0","0","Ctrl+Shift+X","Key Press","X","L Ctrl+L Shift"
"4","7","0","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"4","0","1","F4","Key Press","F4",""
"4","1","1","Ctrl+O","Key Press","O","L Ctrl"
"4","7","1","Ctrl+S","Key Press","S","L Ctrl"
"4","10","1","MB3","Mouse Key Press","MB3",""
"4","12","1","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"4","1","2","Win+.","Key Press","Period and GreaterThan","L GUI"
"4","2","2","Ctrl+Shift+Esc","Key Press","Escape","L Ctrl+L Shift"
"4","3","2","Alt+Shift","Key Press","Shift","L Alt"
"4","4","2","Excel","Toggle Layer","Layer::10",""
"4","5","2","Win+;","Key Press","SemiColon and Colon","L GUI"
"4","7","2","Ctrl+Up","Key Press","UpArrow","L Ctrl"
"4","8","2","Ctrl+End","Key Press","End","L Ctrl"
"4","10","2","F12","Key Press","F12",""
"4","12","2","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"4","0","3","Ctrl+I","Key Press","I","L Ctrl"
"4","2","3","DMS","Toggle Layer","Layer::9",""
"4","3","3","Ctrl+D","Key Press","D","L Ctrl"
"4","5","3","Ctrl+1","Key Press","1 and Bang","L Ctrl"
"4","7","3","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"4","8","3","F5","Key Press","F5",""
"4","9","3","F11","Key Press","F11",""
"4","10","3","F7","Key Press","F7",""
"4","11","3","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"4","12","3","Ctrl+Shift+A","Key Press","A","L Ctrl+L Shift"
"4","3","4","Alt+Click","Mouse Key Press","MB1","L Alt"
"4","4","4","Ctrl+T","Key Press","T","L Ctrl"
"4","5","4","MB1","Mouse Key Press","MB1",""
"4","7","4","Win+Ctrl+D","Key Press","D","L GUI+L Ctrl"
"4","8","4","F9","Key Press","F9",""
"4","4","5","Ctrl+Down","Key Press","DownArrow","L Ctrl"
"4","5","5","Scroll","Momentary Layer","Layer::6",""
"4","7","5","Ctrl+Page Down","Key Press","PageDown","L Ctrl"
"5","2","0","Shift+F5","Key Press","F5","L Shift"
"5","7","0","Win+T","Key Press","T","L GUI"
"5","8","0","Ctrl+G","Key Press","G","L Ctrl"
"5","9","0","Win+Ctrl+D","Key Press","D","L GUI+L Ctrl"
"5","10","0","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"5","9","1","Ctrl+W","Key Press","W","L Ctrl"
"5","10","1","F1","Key Press","F1",""
"5","0","2","Ctrl+N","Key Press","N","L Ctrl"
"5","1","2","Ctrl+S","Key Press","S","L Ctrl"
"5","2","2","Ctrl+J","Key Press","J","L Ctrl"
"5","4","2","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"5","5","2","Win+E","Key Press","E","L GUI"
"5","7","2","Ctrl+Shift+Left","Key Press","LeftArrow","L Ctrl+L Shift"
"5","8","2","Ctrl+Shift+Right","Key Press","RightArrow","L Ctrl+L Shift"
"5","9","2","Ctrl+L","Key Press","L","L Ctrl"
"5","10","2","Ctrl+Shift+Up","Key Press","UpArrow","L Ctrl+L Shift"
"5","12","2","Ctrl+Shift+Down","Key Press","DownArrow","L Ctrl+L Shift"
"5","1","3","Ctrl+2","Key Press","2 and At","L Ctrl"
"5","5","3","F8","Key Press","F8",""
"5","8","3","Win+R","Key Press","R","L GUI"
"5","4","4","MB2","Mouse Key Press","MB2",""
"5","5","4","Ctrl+Y","Key Press","Y","L Ctrl"
"5","8","4","MB4","Mouse Key Press","MB4",""
"5","4","5","Ctrl+Space","Key Press","Spacebar","L Ctrl"
"5","5","5","Ctrl+Shift++","Key Press","Equals and Plus","L Ctrl+L Shift"
"5","7","5","Alt+=","Key Press","Equals and Plus","L Alt"
"6","8","0","Ctrl+Q","Key Press","Q","L Ctrl"
"6","3","1","F10","Key Press","F10",""
"6","4","1","Ctrl+G","Key Press","G","L Ctrl"
"6","7","1","Ctrl+Shift+R","Key Press","R","L Ctrl+L Shift"
"6","9","1","Ctrl+5","Key Press","5 and Percent","L Ctrl"
"6","0","2","Ctrl+Shift+G","Key Press","G","L Ctrl+L Shift"
"6","1","2","Alt+D","Key Press","D","L Alt"
"6","2","2","F9","Key Press","F9",""
"6","3","2","Shift+Space","Key Press","Spacebar","L Shift"
"6","4","2","Ctrl+3","Key Press","3 and Hash","L Ctrl"
"6","8","2","Ctrl+4","Key Press","4 and Dollar","L Ctrl"
"6","10","2","Ctrl++","Key Press","Equals and Plus","L Ctrl"
"6","12","2","Ctrl+Shift+J","Key Press","J","L Ctrl+L Shift"
"6","3","3","Shift+F11","Key Press","F11","L Shift"
"6","5","3","Win+Right","Key Press","RightArrow","L GUI"
"6","7","3","Ctrl+Shift+I","Key Press","I","L Ctrl+L Shift"
"6","8","3","Ctrl+Shift+T","Key Press","T","L Ctrl+L Shift"
"6","9","3","Ctrl+6","Key Press","6 and Caret","L Ctrl"
"6","4","4","Ctrl+E","Key Press","E","L Ctrl"
"6","5","4","Shift+Alt+A","Key Press","A","L Shift+L Alt"
"6","7","4","Shift+Enter","Key Press","Return Enter","L Shift"
"6","8","4","Ctrl+B","Key Press","B","L Ctrl"
"6","4","5","Alt+F","Key Press","F","L Alt"
"6","5","5","Ctrl+,","Key Press","Comma and LessThan","L Ctrl"
"6","7","5","Ctrl+\","Key Press","Backslash and Pipe","L Ctrl"
"7","1","1","9 PU","Key Press","9 and PageUp",""
"7","2","1","↑","Key Press","UpArrow",""
"7","3","1","3 PD","Key Press","3 and PageDn",""
"7","9","1","3 PD","Key Press","3 and PageDn",""
"7","10","1","↑","Key Press","UpArrow",""
"7","11","1","9 PU","Key Press","9 and PageUp",""
"7","1","2","←","Key Press","LeftArrow",""
"7","2","2","↓","Key Press","DownArrow",""
"7","3","2","→","Key Press","RightArrow",""
"7","4","2","Z","Key Press","Z",""
"7","8","2","Z","Key Press","Z",""
"7","9","2","←","Key Press","LeftArrow",""
"7","10","2","↓","Key Press","DownArrow",""
"7","11","2","→","Key Press","RightArrow",""
"7","1","3","X","Key Press","X",""
"7","2","3","C","Key Press","C",""
"7","3","3","Shft","Key Press","LeftShift",""
"7","4","3","Esc","Key Press","Escape",""
"7","8","3","Esc","Key Press","Escape",""
"7","9","3","Shft","Key Press","LeftShift",""
"7","10","3","C","Key Press","C",""
"7","11","3","X","Key Press","X",""
"7","3","4","Exit Base","coach_base","",""
"7","4","4","␣","Key Press","Spacebar",""
"7","5","4","Exit Base","coach_base","",""
"7","7","4","Exit Base","coach_base","",""
"7","8","4","Exit Base","coach_base","",""
"7","4","5","Click","Mouse Key Press","MB1",""
"7","5","5","Right Click","Mouse Key Press","MB2",""
"7","7","5","Ret","Key Press","Return Enter",""
"8","9","0","Ctrl+Shift+End","Key Press","End","L Ctrl+L Shift"
"8","12","0","Down","Key Press","DownArrow",""
"8","3","1","Alt+Shift+D","Key Press","D","L Alt+L Shift"
"8","7","1","F11","Key Press","F11",""
"8","8","1","Ctrl+Shift+Z","Key Press","Z","L Ctrl+L Shift"
"8","10","1","Ctrl+Z","Key Press","Z","L Ctrl"
"8","0","2","Shift+Alt+Up","Key Press","UpArrow","L Shift+L Alt"
"8","1","2","Ctrl+Shift+Enter","Key Press","Return Enter","L Ctrl+L Shift"
"8","2","2","Win+Tab","Key Press","Tab","L GUI"
"8","3","2","Ctrl+V","Key Press","V","L Ctrl"
"8","4","2","Ctrl+[","Key Press","Left Brace","L Ctrl"
"8","5","2","Speed","Momentary Layer","Layer::8",""
"8","7","2","Ctrl+K Ctrl+F","Key Press","F","L Ctrl+K Ctrl"
"8","8","2","Alt+F4","Key Press","F4","L Alt"
"8","9","2","Shift+F3","Key Press","F3","L Shift"
"8","10","2","Ctrl+C","Key Press","C","L Ctrl"
"8","11","2","Shift+Alt+Left","Key Press","LeftArrow","L Shift+L Alt"
"8","12","2","Shift+Click","Mouse Key Press","MB1","L Shift"
"8","3","3","Ctrl+Shift+B","Key Press","B","L Ctrl+L Shift"
"8","4","3","Ctrl+Shift+O","Key Press","O","L Ctrl+L Shift"
"8","8","3","Ctrl+Shift+$","Key Press","4 and Dollar","L Ctrl+L Shift"
"8","10","3","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"8","3","4","Code","Toggle Layer","Layer::5",""
"8","4","4","coach_game_lock","coach_game_lock","",""
"8","5","4","Win+Up","Key Press","UpArrow","L GUI"
"8","7","4","Exit Travel","coach_travel_off","",""
"8","8","4","Win+Down","Key Press","DownArrow","L GUI"
"8","5","5","F10","Key Press","F10",""
"8","7","5","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"9","1","1","Ctrl+Shift+W","Key Press","W","L Ctrl+L Shift"
"9","2","1","Ctrl+Shift+A","Key Press","A","L Ctrl+L Shift"
"9","4","1","Ctrl+M","Key Press","M","L Ctrl"
"9","7","1","Ctrl+P","Key Press","P","L Ctrl"
"9","8","1","Win+P","Key Press","P","L GUI"
"9","1","2","Ctrl+S","Key Press","S","L Ctrl"
"9","2","2","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"9","7","2","Ctrl+Shift+Q","Key Press","Q","L Ctrl+L Shift"
"9","9","2","Win+B","Key Press","B","L GUI"
"9","10","2","Win+Left","Key Press","LeftArrow","L GUI"
"9","12","2","Ctrl+Shift+U","Key Press","U","L Ctrl+L Shift"
"9","1","3","Ctrl+Shift+D","Key Press","D","L Ctrl+L Shift"
"9","2","3","Ctrl+O","Key Press","O","L Ctrl"
"9","3","3","Ctrl+Shift+X","Key Press","X","L Ctrl+L Shift"
"9","4","3","Ctrl+Shift+F5","Key Press","F5","L Ctrl+L Shift"
"9","5","3","Ctrl+F5","Key Press","F5","L Ctrl"
"9","8","3","Ctrl+Page Up","Key Press","PageUp","L Ctrl"
"9","3","4","Win+Shift+Left","Key Press","LeftArrow","L GUI+L Shift"
"9","4","4","Win+Shift+Right","Key Press","RightArrow","L GUI+L Shift"
"9","5","4","Win+V","Key Press","V","L GUI"
"9","7","4","=","Key Press","Equals and Plus",""
"9","4","5","Ctrl+;","Key Press","SemiColon and Colon","L Ctrl"
"9","5","5","Ctrl+Shift+!","Key Press","1 and Bang","L Ctrl+L Shift"
"10","1","0","Ctrl+A","Key Press","A","L Ctrl"
"10","2","0","Ctrl+C","Key Press","C","L Ctrl"
"10","3","0","Ctrl+X","Key Press","X","L Ctrl"
"10","5","1","Ctrl+-","Key Press","Dash and Underscore","L Ctrl"
"10","8","1","Ctrl+Shift+Home","Key Press","Home","L Ctrl+L Shift"
"10","11","1","Win+B","Key Press","B","L GUI"
"10","0","2","Ctrl+F","Key Press","F","L Ctrl"
"10","1","2","Ctrl+S","Key Press","S","L Ctrl"
"10","3","2","Ctrl+Shift+%","Key Press","5 and Percent","L Ctrl+L Shift"
"10","5","2","Alt+Shift+-","Key Press","Dash and Underscore","L Alt+L Shift"
"10","7","2","Win+L","Key Press","L","L GUI"
"10","8","2","Ctrl+]","Key Press","Right Brace","L Ctrl"
"10","9","2","Alt+Shift++","Key Press","Equals and Plus","L Alt+L Shift"
"10","11","2","Win+2","Key Press","2 and At","L GUI"
"10","12","2","Win+N","Key Press","N","L GUI"
"10","1","3","Win+M","Key Press","M","L GUI"
"10","3","3","Ctrl+Shift+1","Key Press","1 and Bang","L Ctrl+L Shift"
"10","5","3","Ctrl+K","Key Press","K","L Ctrl"
"10","8","3","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"10","10","3","Ctrl+End","Key Press","End","L Ctrl"
"10","3","4","Ctrl+.","Key Press","Period and GreaterThan","L Ctrl"
"10","4","4","Ctrl+Shift+Tab","Key Press","Tab","L Ctrl+L Shift"
"10","5","4","Ctrl+Shift+`","Key Press","Grave Accent and Tilde","L Ctrl+L Shift"
"10","7","4","Win+T","Key Press","T","L GUI"
"10","8","4","Alt+Up","Key Press","UpArrow","L Alt"
"10","4","5","Page Down","Key Press","PageDown",""
"10","5","5","Page Up","Key Press","PageUp",""
"10","7","5","Win+Ctrl+D","Key Press","D","L GUI+L Ctrl"`;

function parseExpected() {
  const lines = EXPECTED_CSV.trim().split('\n');
  const headers = lines[0].split(',').map(h => h.split(String.fromCharCode(34)).join('').trim());
  const out = [];
  for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split(',').map(p => p.split(String.fromCharCode(34)).join('').trim());
    const obj = {};
    for (let j = 0; j < headers.length; j++) obj[headers[j]] = parts[j] || '';
    out.push(obj);
  }
  return out;
}

function runVerify() {
  const expected = parseExpected();
  let pass = 0, fail = 0, errors = [];
  for (const exp of expected) {
    const layer = parseInt(exp.layer);
    const x = parseInt(exp.x);
    const y = parseInt(exp.y);
    const actual = getKeyBinding(layer, x, y);
    if (!actual) {
      fail++;
      errors.push({layer, x, y, expected: exp, error: 'key not found'});
      continue;
    }
    const bMatch = actual.behavior.toLowerCase() === exp.behavior.toLowerCase();
    const pMatch = actual.parameter.toLowerCase() === exp.parameter.toLowerCase();
    const mMatch = actual.modifiers === exp.modifiers;
    if (bMatch && pMatch && mMatch) {
      pass++;
    } else {
      fail++;
      errors.push({layer, x, y, expected: exp, actual});
    }
  }
  console.log('Verify result: ' + pass + ' pass, ' + fail + ' fail (' + (pass/(pass+fail)*100).toFixed(1) + '%)');
  window._CHARYBDIS_VERIFY_RESULT = {pass, fail, errors};
}

runVerify();
