// ZMK Studio verify script for evolved V2 layout
window.CHARYBDIS_VERSION = "evolved-v2";

function getKeyBinding(layer, x, y) {
  const btn = document.querySelector(`[data-layer='${layer}'][data-x='${x}'][data-y='${y}']`);
  if (!btn) return null;
  const behavior = btn.querySelector('.behavior-name')?.textContent?.trim() || '';
  const parameter = btn.querySelector('.parameter-name')?.textContent?.trim() || '';
  const modifiers = Array.from(btn.querySelectorAll('.modifier-tag')).map(m => m.textContent.trim()).join('+');
  return {behavior, parameter, modifiers};
}

const EXPECTED_CSV = `"layer","x","y","label","behavior","parameter","modifiers"
"0","0","0","Esc","Key Press","Escape",""
"0","1","0","1","Key Press","1 and Bang",""
"0","2","0","2","Key Press","2 and At",""
"0","3","0","3","Key Press","3 and Hash",""
"0","4","0","4","Key Press","4 and Dollar",""
"0","5","0","5","Key Press","5 and Percent",""
"0","7","0","6","Key Press","6 and Caret",""
"0","8","0","7","Key Press","7 and Ampersand",""
"0","9","0","8","Key Press","8 and Star",""
"0","10","0","9","Key Press","9 and Left Bracket",""
"0","11","0","0","Key Press","0 and Right Bracket",""
"0","12","0","BkSp","Key Press","Delete",""
"0","0","1","Tab","Key Press","Tab",""
"0","1","1","Q","Key Press","Q",""
"0","2","1","W","Key Press","W",""
"0","3","1","E","Key Press","E",""
"0","4","1","R","Key Press","R",""
"0","5","1","T","Key Press","T",""
"0","7","1","Y","Key Press","Y",""
"0","8","1","U","Key Press","U",""
"0","9","1","I","Key Press","I",""
"0","10","1","O","Key Press","O",""
"0","11","1","P","Key Press","P",""
"0","12","1","å","Key Press","Left Brace",""
"0","0","2","Shft","Key Press","LeftShift",""
"0","1","2","A","Key Press","A",""
"0","2","2","S","Key Press","S",""
"0","3","2","D","Key Press","D",""
"0","4","2","F","Key Press","F",""
"0","5","2","G","Key Press","G",""
"0","7","2","H","Key Press","H",""
"0","8","2","J","Key Press","J",""
"0","9","2","K","Key Press","K",""
"0","10","2","L","Key Press","L",""
"0","11","2","ø","Key Press","SemiColon and Colon",""
"0","12","2","æ","Key Press","Left Apos and Double",""
"0","0","3","Ctrl","Key Press","LeftControl",""
"0","1","3","Z","Key Press","Z",""
"0","2","3","X","Key Press","X",""
"0","3","3","C","Key Press","C",""
"0","4","3","V","Key Press","V",""
"0","5","3","B","Key Press","B",""
"0","7","3","N","Key Press","N",""
"0","8","3","M","Key Press","M",""
"0","9","3",",","Key Press","Comma and LessThan",""
"0","10","3",".","Key Press","Period and GreaterThan",""
"0","11","3","/","Key Press","ForwardSlash and QuestionMark",""
"0","12","3","\","Key Press","Backslash and Pipe",""
"0","3","4","Nav","coach_l1_hold","",""
"0","4","4","␣","Key Press","Spacebar",""
"0","5","4","Ctrl+Shift+F5","Key Press","F5","L Ctrl+L Shift"
"0","7","4","System","coach_l4_hold","",""
"0","8","4","Window","coach_l3_hold","",""
"0","7","5","Ret","Key Press","Return Enter",""
"1","1","0","Shift+F3","Key Press","F3","L Shift"
"1","2","0","Ctrl+Shift+\","Key Press","Backslash and Pipe","L Ctrl+L Shift"
"1","3","0","Shift+Alt+Up","Key Press","UpArrow","L Shift+L Alt"
"1","5","0","Ctrl+Shift+Down","Key Press","DownArrow","L Ctrl+L Shift"
"1","7","0","Ctrl+H","Key Press","H","L Ctrl"
"1","8","0","Shift+Enter","Key Press","Return Enter","L Shift"
"1","9","0","Win+Ctrl+F4","Key Press","F4","L GUI+L Ctrl"
"1","10","0","Win+K","Key Press","K","L GUI"
"1","11","0","Ctrl+Shift+Q","Key Press","Q","L Ctrl+L Shift"
"1","12","0","Ctrl+8","Key Press","8 and Star","L Ctrl"
"1","2","1","ScrollUp","Key Press","ScrollUp",""
"1","4","1","Ctrl+Shift+W","Key Press","W","L Ctrl+L Shift"
"1","5","1","Ctrl+1","Key Press","1 and Bang","L Ctrl"
"1","7","1","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"1","8","1","Ctrl+2","Key Press","2 and At","L Ctrl"
"1","9","1","Ctrl+F5","Key Press","F5","L Ctrl"
"1","10","1","Win+N","Key Press","N","L GUI"
"1","0","2","Ctrl+O","Key Press","O","L Ctrl"
"1","1","2","Ctrl+Alt+Down","Key Press","DownArrow","L Ctrl+L Alt"
"1","2","2","Alt+Up","Key Press","UpArrow","L Alt"
"1","5","2","Alt+Down","Key Press","DownArrow","L Alt"
"1","7","2","Ctrl+Shift+M","Key Press","M","L Ctrl+L Shift"
"1","8","2","Ctrl+Shift+O","Key Press","O","L Ctrl+L Shift"
"1","9","2","Ctrl+E","Key Press","E","L Ctrl"
"1","10","2","MB4","Mouse Key Press","MB4",""
"1","11","2","Ctrl+Shift+T","Key Press","T","L Ctrl+L Shift"
"1","0","3","Ctrl+,","Key Press","Comma and LessThan","L Ctrl"
"1","1","3","Ctrl+]","Key Press","]","L Ctrl"
"1","2","3","Ctrl+K S","Key Press","K S","L Ctrl"
"1","3","3","F7","Key Press","F7",""
"1","4","3","Win+M","Key Press","M","L GUI"
"1","5","3","Ctrl+S","Key Press","S","L Ctrl"
"1","7","3","Ctrl+0","Key Press","0 and Right Bracket","L Ctrl"
"1","8","3","Page Down","Key Press","DownArrow","Page"
"1","10","3","Alt+Shift+Up","Key Press","UpArrow","L Alt+L Shift"
"1","11","3","Ctrl+[","Key Press","[","L Ctrl"
"1","12","3","Ctrl+Shift+>","Key Press",">","L Ctrl+L Shift"
"1","3","4","Ctrl+Shift++","Key Press","+","L Ctrl+L Shift"
"1","4","4","Up","Key Press","UpArrow",""
"1","5","4","Ctrl+K Ctrl+S","Key Press","S","L Ctrl+K Ctrl"
"1","7","4","MB5","Mouse Key Press","MB5",""
"1","8","4","Ctrl+I","Key Press","I","L Ctrl"
"1","5","5","Win+Shift+Right","Key Press","RightArrow","L GUI+L Shift"
"2","1","0","MB1","Mouse Key Press","MB1",""
"2","3","0","Ctrl+Shift+$","Key Press","$","L Ctrl+L Shift"
"2","9","0","Ctrl+J","Key Press","J","L Ctrl"
"2","10","0","Ctrl+U","Key Press","U","L Ctrl"
"2","0","1","Win+Right","Key Press","RightArrow","L GUI"
"2","1","1","Ctrl+M","Key Press","M","L Ctrl"
"2","2","1","F10","Key Press","F10",""
"2","3","1","Ctrl+W","Key Press","W","L Ctrl"
"2","4","1","Win+5","Key Press","5 and Percent","L GUI"
"2","5","1","Ctrl+R","Key Press","R","L Ctrl"
"2","7","1","Alt+F","Key Press","F","L Alt"
"2","8","1","Ctrl+Shift+P","Key Press","P","L Ctrl+L Shift"
"2","9","1","yy","Key Press","yy",""
"2","10","1","F8","Key Press","F8",""
"2","12","1","Ctrl+K Ctrl+F","Key Press","F","L Ctrl+K Ctrl"
"2","3","2","Shift+Alt+Right","Key Press","RightArrow","L Shift+L Alt"
"2","4","2","Win+X","Key Press","X","L GUI"
"2","5","2","Ctrl+Shift+9","Key Press","9 and Left Bracket","L Ctrl+L Shift"
"2","7","2","Ctrl+4","Key Press","4 and Dollar","L Ctrl"
"2","8","2","Ctrl+Shift+X","Key Press","X","L Ctrl+L Shift"
"2","0","3","Ctrl+Shift+U","Key Press","U","L Ctrl+L Shift"
"2","1","3","Alt+Shift+D","Key Press","D","L Alt+L Shift"
"2","2","3","Win+Space","Key Press","Spacebar","L GUI"
"2","3","3","Win+R","Key Press","R","L GUI"
"2","5","3","Win+Home","Key Press","Home","L GUI"
"2","7","3","F11","Key Press","F11",""
"2","8","3","F4","Key Press","F4",""
"2","9","3","Ctrl+Shift+D","Key Press","D","L Ctrl+L Shift"
"2","10","3","Ctrl+Shift+2","Key Press","2 and At","L Ctrl+L Shift"
"2","12","3","Alt+=","Key Press","=","L Alt"
"2","4","4","Ctrl+Shift+Left","Key Press","LeftArrow","L Ctrl+L Shift"
"2","5","4","MB3","Mouse Key Press","MB3",""
"2","7","4","Win+S","Key Press","S","L GUI"
"2","8","4","MB2","Mouse Key Press","MB2",""
"2","7","5","Ctrl+7","Key Press","7 and Ampersand","L Ctrl"
"3","0","0","Win+Down","Key Press","DownArrow","L GUI"
"3","1","0","Ctrl+Right","Key Press","RightArrow","L Ctrl"
"3","2","0","Win+Ctrl+Left","Key Press","LeftArrow","L GUI+L Ctrl"
"3","3","0","Ctrl+Shift+N","Key Press","N","L Ctrl+L Shift"
"3","4","0","F5","Key Press","F5",""
"3","7","0","Ctrl+`","Key Press","`","L Ctrl"
"3","8","0","Ctrl+V","Key Press","V","L Ctrl"
"3","9","0","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"3","10","0","Win+.","Key Press","Period and GreaterThan","L GUI"
"3","11","0","F12","Key Press","F12",""
"3","0","1","Ctrl+.","Key Press","Period and GreaterThan","L Ctrl"
"3","1","1","Shift+F5","Key Press","F5","L Shift"
"3","2","1","Win+4","Key Press","4 and Dollar","L GUI"
"3","3","1","Win+Ctrl+Right","Key Press","RightArrow","L GUI+L Ctrl"
"3","5","1","Ctrl+Left","Key Press","LeftArrow","L Ctrl"
"3","7","1","Ctrl+N","Key Press","N","L Ctrl"
"3","8","1","Ctrl+Shift+Up","Key Press","UpArrow","L Ctrl+L Shift"
"3","9","1","Ctrl+6","Key Press","6 and Caret","L Ctrl"
"3","10","1","Ctrl+Y","Key Press","Y","L Ctrl"
"3","12","1","Down","Key Press","DownArrow",""
"3","0","2","Win+Up","Key Press","UpArrow","L GUI"
"3","1","2","Ctrl++","Key Press","+","L Ctrl"
"3","2","2","Alt+Click","Mouse Key Press","MB1","L Alt"
"3","3","2","Win+Shift+Left","Key Press","LeftArrow","L GUI+L Shift"
"3","4","2","Win+C","Key Press","C","L GUI"
"3","7","2","F2","Key Press","F2",""
"3","8","2","Ctrl+C","Key Press","C","L Ctrl"
"3","9","2","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"3","11","2","Alt+D","Key Press","D","L Alt"
"3","12","2","=","Key Press","=",""
"3","0","3","Ctrl+Alt+Up","Key Press","UpArrow","L Ctrl+L Alt"
"3","1","3","Ctrl+Shift+Z","Key Press","Z","L Ctrl+L Shift"
"3","3","3","Win+Left","Key Press","LeftArrow","L GUI"
"3","5","3","Shift+Alt+A","Key Press","A","L Shift+L Alt"
"3","7","3","Ctrl+A","Key Press","A","L Ctrl"
"3","8","3","Ctrl+Down","Key Press","DownArrow","L Ctrl"
"3","9","3","Ctrl+9","Key Press","9 and Left Bracket","L Ctrl"
"3","11","3","Ctrl+-","Key Press","-","L Ctrl"
"3","3","4","Alt+Tab","Key Press","Tab","L Alt"
"3","4","4","Ctrl+End","Key Press","End","L Ctrl"
"3","7","4","Ctrl+Page Down","Key Press","Page Down","L Ctrl"
"3","8","4","Alt+F4","Key Press","F4","L Alt"
"3","4","5","Shift+Alt+Down","Key Press","DownArrow","L Shift+L Alt"
"3","5","5","Win+Shift+S","Key Press","S","L GUI+L Shift"
"3","7","5","F1","Key Press","F1",""
"4","0","0","Win+1","Key Press","1 and Bang","L GUI"
"4","1","0","Ctrl+K Ctrl+W","Key Press","W","L Ctrl+K Ctrl"
"4","2","0","Page Up","Key Press","UpArrow","Page"
"4","4","0","Win+I","Key Press","I","L GUI"
"4","5","0","Alt+P","Key Press","P","L Alt"
"4","7","0","Ctrl+F","Key Press","F","L Ctrl"
"4","9","0","Ctrl+Shift+G","Key Press","G","L Ctrl+L Shift"
"4","10","0","Ctrl+Shift+~","Key Press","~","L Ctrl+L Shift"
"4","11","0","Win+A","Key Press","A","L GUI"
"4","12","0","Ctrl+Home","Key Press","Home","L Ctrl"
"4","0","1","Win+V","Key Press","V","L GUI"
"4","1","1","Ctrl+Shift+<","Key Press","<","L Ctrl+L Shift"
"4","2","1","Shift+Delete","Key Press","Dash and Underscore","L Shift"
"4","3","1","Ctrl+Z","Key Press","Z","L Ctrl"
"4","4","1","Win+L","Key Press","L","L GUI"
"4","5","1","Alt+Enter","Key Press","Return Enter","L Alt"
"4","7","1","Ctrl+Shift+%","Key Press","%","L Ctrl+L Shift"
"4","8","1","Ctrl+T","Key Press","T","L Ctrl"
"4","10","1","Ctrl+D","Key Press","D","L Ctrl"
"4","0","2","Ctrl+Shift+C","Key Press","C","L Ctrl+L Shift"
"4","1","2","Ctrl+Shift+Home","Key Press","Home","L Ctrl+L Shift"
"4","2","2","Win+E","Key Press","E","L GUI"
"4","3","2","Alt+Home","Key Press","Home","L Alt"
"4","4","2","Win+Pause","Key Press","Pause","L GUI"
"4","5","2","Shift+Space","Key Press","Spacebar","L Shift"
"4","7","2","Ctrl+Shift+B","Key Press","B","L Ctrl+L Shift"
"4","8","2","Ctrl+Shift+A","Key Press","A","L Ctrl+L Shift"
"4","9","2","Ctrl+B","Key Press","B","L Ctrl"
"4","10","2","Ctrl+/","Key Press","ForwardSlash and QuestionMark","L Ctrl"
"4","11","2","Win+T","Key Press","T","L GUI"
"4","3","3","?","Key Press","?",""
"4","4","3","Ctrl+Click","Mouse Key Press","MB1","L Ctrl"
"4","5","3","Ctrl+3","Key Press","3 and Hash","L Ctrl"
"4","7","3","Ctrl+L","Key Press","L","L Ctrl"
"4","8","3","Alt+Shift+-","Key Press","-","L Alt+L Shift"
"4","9","3","Alt+Right","Key Press","RightArrow","L Alt"
"4","10","3","Ctrl+Shift+!","Key Press","!","L Ctrl+L Shift"
"4","3","4","Win+Tab","Key Press","Tab","L GUI"
"4","5","4","Shift+Click","Mouse Key Press","MB1","L Shift"
"4","7","5","Win+P","Key Press","P","L GUI"
"5","1","0","Ctrl+Shift+R","Key Press","R","L Ctrl+L Shift"
"5","3","0","Ctrl+Shift+Del","Key Press","Del","L Ctrl+L Shift"
"5","7","0","Ctrl+Shift+Tab","Key Press","Tab","L Ctrl+L Shift"
"5","9","0","gi","Key Press","gi",""
"5","7","2","Ctrl+Enter","Key Press","Return Enter","L Ctrl"
"5","9","2","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"5","5","3","Ctrl+Shift+Enter","Key Press","Return Enter","L Ctrl+L Shift"
"6","2","0","Ctrl+Shift+Esc","Key Press","Escape","L Ctrl+L Shift"
"6","8","0","Ctrl+Shift+Right","Key Press","RightArrow","L Ctrl+L Shift"
"6","3","1","Ctrl+5","Key Press","5 and Percent","L Ctrl"
"6","4","1","Ctrl+Shift+End","Key Press","End","L Ctrl+L Shift"
"6","7","1","Ctrl+Tab","Key Press","Tab","L Ctrl"
"6","12","1","Ctrl+Shift+I","Key Press","I","L Ctrl+L Shift"
"6","2","2","gg","Key Press","gg",""
"6","9","2","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"6","10","3","Ctrl+Shift+F","Key Press","F","L Ctrl+L Shift"
"6","3","4","Ctrl+Shift+1","Key Press","1 and Bang","L Ctrl+L Shift"
"6","7","4","Ctrl+Shift+J","Key Press","J","L Ctrl+L Shift"
"6","8","4","Ctrl+F6","Key Press","F6","L Ctrl"
"6","5","5","Ctrl+;","Key Press","SemiColon and Colon","L Ctrl"
"7","1","1","9 PU","Key Press","9 and PageUp",""
"7","2","1","UpArrow","Key Press","UpArrow",""
"7","3","1","3 PD","Key Press","3 and PageDn",""
"7","9","1","3 PD","Key Press","3 and PageDn",""
"7","10","1","UpArrow","Key Press","UpArrow",""
"7","11","1","9 PU","Key Press","9 and PageUp",""
"7","1","2","LeftArrow","Key Press","LeftArrow",""
"7","2","2","DownArrow","Key Press","DownArrow",""
"7","3","2","RightArrow","Key Press","RightArrow",""
"7","4","2","Z","Key Press","Z",""
"7","8","2","Z","Key Press","Z",""
"7","9","2","LeftArrow","Key Press","LeftArrow",""
"7","10","2","DownArrow","Key Press","DownArrow",""
"7","11","2","RightArrow","Key Press","RightArrow",""
"7","1","3","X","Key Press","X",""
"7","2","3","C","Key Press","C",""
"7","3","3","Shft","Key Press","LeftShift",""
"7","4","3","Esc","Key Press","Escape",""
"7","8","3","Esc","Key Press","Escape",""
"7","9","3","Shft","Key Press","LeftShift",""
"7","10","3","C","Key Press","C",""
"7","11","3","X","Key Press","X",""
"7","4","4","␣","Key Press","Spacebar",""
"7","7","5","Ret","Key Press","Return Enter",""
"8","1","1","Shift+Tab","Key Press","Tab","L Shift"
"8","4","1","Alt+Left","Key Press","LeftArrow","L Alt"
"8","9","1","Win+;","Key Press","SemiColon and Colon","L GUI"
"8","3","2","Ctrl+Q","Key Press","Q","L Ctrl"
"8","5","2","Win+B","Key Press","B","L GUI"
"8","7","2","Ctrl+P","Key Press","P","L Ctrl"
"8","4","4","Shift+Alt+Left","Key Press","LeftArrow","L Shift+L Alt"
"8","8","4","Ctrl+X","Key Press","X","L Ctrl"
"9","1","1","Alt+Shift++","Key Press","+","L Alt+L Shift"
"9","2","1","Ctrl+\","Key Press","Backslash and Pipe","L Ctrl"
"9","4","1","Ctrl+Shift+`","Key Press","`","L Ctrl+L Shift"
"9","5","1","Ctrl+Shift+F6","Key Press","F6","L Ctrl+L Shift"
"9","7","1","Ctrl+Shift+L","Key Press","L","L Ctrl+L Shift"
"9","8","1","Win+2","Key Press","2 and At","L GUI"
"9","3","2","Win+D","Key Press","D","L GUI"
"9","8","2","Win+H","Key Press","H","L GUI"
"9","10","2","Ctrl+Shift+6","Key Press","6 and Caret","L Ctrl+L Shift"
"9","9","3","Ctrl+K","Key Press","K","L Ctrl"
"9","11","3","F3","Key Press","F3",""
"9","3","4","Shift+F11","Key Press","F11","L Shift"
"9","4","5","Win+Ctrl+D","Key Press","D","L GUI+L Ctrl"
"10","0","0","Win+3","Key Press","3 and Hash","L GUI"
"10","3","0","Ctrl+Shift+;","Key Press","SemiColon and Colon","L Ctrl+L Shift"
"10","7","0","Alt+Shift+Down","Key Press","DownArrow","L Alt+L Shift"
"10","8","0","Ctrl+Up","Key Press","UpArrow","L Ctrl"
"10","7","1","Ctrl+Page Up","Key Press","Page Up","L Ctrl"
"10","2","2","Ctrl+Space","Key Press","Spacebar","L Ctrl"
"10","3","2","Shift+F8","Key Press","F8","L Shift"
"10","8","2","Alt+F12","Key Press","F12","L Alt"
"10","3","3","Ctrl+G","Key Press","G","L Ctrl"
"10","7","3","ScrollDown","Key Press","ScrollDown",""
"10","8","3","F9","Key Press","F9",""
"10","5","5","Alt+Shift","Key Press","Shift","L Alt"`;

function parseExpected() {
  const lines = EXPECTED_CSV.trim().split('\n');
  const headers = lines[0].split(',').map(h => h.split(String.fromCharCode(34)).join('').trim());
  const out = [];
  for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split(',').map(p => p.split(String.fromCharCode(34)).join('').trim());
    const obj = {};
    for (let j = 0; j < headers.length; j++) obj[headers[j]] = parts[j] || '';
    out.push(obj);
  }
  return out;
}

function runVerify() {
  const expected = parseExpected();
  let pass = 0, fail = 0, errors = [];
  for (const exp of expected) {
    const layer = parseInt(exp.layer);
    const x = parseInt(exp.x);
    const y = parseInt(exp.y);
    const actual = getKeyBinding(layer, x, y);
    if (!actual) {
      fail++;
      errors.push({layer, x, y, expected: exp, error: 'key not found'});
      continue;
    }
    const bMatch = actual.behavior.toLowerCase() === exp.behavior.toLowerCase();
    const pMatch = actual.parameter.toLowerCase() === exp.parameter.toLowerCase();
    const mMatch = actual.modifiers === exp.modifiers;
    if (bMatch && pMatch && mMatch) {
      pass++;
    } else {
      fail++;
      errors.push({layer, x, y, expected: exp, actual});
    }
  }
  console.log('Verify result: ' + pass + ' pass, ' + fail + ' fail (' + (pass/(pass+fail)*100).toFixed(1) + '%)');
  window._CHARYBDIS_VERIFY_RESULT = {pass, fail, errors};
}

runVerify();
