// ZMK Studio verify script for evolved V2 layout
window.CHARYBDIS_VERSION = "evolved-v2";

function getKeyBinding(layer, x, y) {
  const btn = document.querySelector(`[data-layer='${layer}'][data-x='${x}'][data-y='${y}']`);
  if (!btn) return null;
  const behavior = btn.querySelector('.behavior-name')?.textContent?.trim() || '';
  const parameter = btn.querySelector('.parameter-name')?.textContent?.trim() || '';
  const modifiers = Array.from(btn.querySelectorAll('.modifier-tag')).map(m => m.textContent.trim()).join('+');
  return {behavior, parameter, modifiers};
}

const EXPECTED_CSV = `
"layer","x","y","label","behavior","parameter","modifiers"
"0","0","0","Esc","Key Press","Escape",""
"0","1","0","1","Key Press","1 and Bang",""
"0","2","0","2","Key Press","2 and At",""
"0","3","0","3","Key Press","3 and Hash",""
"0","4","0","4","Key Press","4 and Dollar",""
"0","5","0","5","Key Press","5 and Percent",""
"0","7","0","6","Key Press","6 and Caret",""
"0","8","0","7","Key Press","7 and Ampersand",""
"0","9","0","8","Key Press","8 and Star",""
"0","10","0","9","Key Press","9 and Left Bracket",""
"0","11","0","0","Key Press","0 and Right Bracket",""
"0","12","0","BkSp","Key Press","Delete",""
"0","0","1","Tab","Key Press","Tab",""
"0","1","1","Q","Key Press","Q",""
"0","2","1","W","Key Press","W",""
"0","3","1","E","Key Press","E",""
"0","4","1","R","Key Press","R",""
"0","5","1","T","Key Press","T",""
"0","7","1","Y","Key Press","Y",""
"0","8","1","U","Key Press","U",""
"0","9","1","I","Key Press","I",""
"0","10","1","O","Key Press","O",""
"0","11","1","P","Key Press","P",""
"0","12","1","å","Key Press","Left Brace",""
"0","0","2","Shft","Key Press","LeftShift",""
"0","1","2","A","Key Press","A",""
"0","2","2","S","Key Press","S",""
"0","3","2","D","Key Press","D",""
"0","4","2","F","Key Press","F",""
"0","5","2","G","Key Press","G",""
"0","7","2","H","Key Press","H",""
"0","8","2","J","Key Press","J",""
"0","9","2","K","Key Press","K",""
"0","10","2","L","Key Press","L",""
"0","11","2","ø","Key Press","SemiColon and Colon",""
"0","12","2","æ","Key Press","Left Apos and Double",""
"0","0","3","Ctrl","Key Press","LeftControl",""
"0","1","3","Z","Key Press","Z",""
"0","2","3","X","Key Press","X",""
"0","3","3","C","Key Press","C",""
"0","4","3","V","Key Press","V",""
"0","5","3","B","Key Press","B",""
"0","7","3","N","Key Press","N",""
"0","8","3","M","Key Press","M",""
"0","9","3",",","Key Press","Comma and LessThan",""
"0","10","3",".","Key Press","Period and GreaterThan",""
"0","11","3","/","Key Press","ForwardSlash and QuestionMark",""
"0","12","3","\","Key Press","Backslash and Pipe",""
"0","3","4","Nav","coach_l1_hold","",""
"0","4","4","␣","Key Press","Spacebar",""
"0","5.0","4.0","Ctrl+Shift+C","Key Press","Keyboard C","L Ctrl+L Shift"
"0","7","4","System","coach_l4_hold","",""
"0","8","4","Window","coach_l3_hold","",""
"0","4.0","5.0","Page Down","Key Press","Keyboard Page Down",""
"0","5.0","5.0","r","Key Press","Keyboard r",""
"0","7","5","Ret","Key Press","Return Enter",""
"1","0.0","0.0","Ctrl+5","Key Press","Keyboard 5 and Percent","L Ctrl"
"1","1.0","0.0","F9","Key Press","Keyboard F9",""
"1","2.0","0.0","Ctrl+Shift+\","Key Press","Keyboard Backslash and Pipe","L Ctrl+L Shift"
"1","3.0","0.0","Alt+F","Key Press","Keyboard F","L Alt"
"1","4.0","0.0","Ctrl+J","Key Press","Keyboard J","L Ctrl"
"1","5.0","0.0","Win+S","Key Press","Keyboard S","L GUI"
"1","7.0","0.0","Ctrl+Z","Key Press","Keyboard Z","L Ctrl"
"1","8.0","0.0","Ctrl+H","Key Press","Keyboard H","L Ctrl"
"1","9.0","0.0","Ctrl+Up","Key Press","Keyboard UpArrow","L Ctrl"
"1","10.0","0.0","Tab","Key Press","Keyboard Tab",""
"1","11.0","0.0","Win+P","Key Press","Keyboard P","L GUI"
"1","12.0","0.0","Alt+Shift+D","Key Press","Keyboard D","L Alt+L Shift"
"1","0.0","1.0","Win+Up","Key Press","Keyboard UpArrow","L GUI"
"1","1.0","1.0","Win+Shift+Left","Key Press","Keyboard LeftArrow","L GUI+L Shift"
"1","2.0","1.0","Win+Home","Key Press","Keyboard Home","L GUI"
"1","3.0","1.0","Ctrl+Shift+F","Key Press","Keyboard F","L Ctrl+L Shift"
"1","4.0","1.0","Enter","Key Press","Keyboard Return Enter",""
"1","5.0","1.0","Ctrl+Left","Key Press","Keyboard LeftArrow","L Ctrl"
"1","7.0","1.0","Ctrl+Shift+>","Key Press","Keyboard Period and GreaterThan","L Ctrl+L Shift"
"1","8.0","1.0","Win+Shift+S","Key Press","Keyboard S","L GUI+L Shift"
"1","9.0","1.0","Win+A","Key Press","Keyboard A","L GUI"
"1","10.0","1.0","Ctrl+Shift+2","Key Press","Keyboard 2 and At","L Ctrl+L Shift"
"1","11.0","1.0","Ctrl+,","Key Press","Keyboard Comma and LessThan","L Ctrl"
"1","12.0","1.0","F4","Key Press","Keyboard F4",""
"1","0.0","2.0","Ctrl+Shift+J","Key Press","Keyboard J","L Ctrl+L Shift"
"1","1.0","2.0","Ctrl+D","Key Press","Keyboard D","L Ctrl"
"1","2.0","2.0","yy","Key Press","Keyboard yy",""
"1","3.0","2.0","Ctrl+Shift+Left","Key Press","Keyboard LeftArrow","L Ctrl+L Shift"
"1","4.0","2.0","Win+H","Key Press","Keyboard H","L GUI"
"1","5.0","2.0","Win+Shift+Right","Key Press","Keyboard RightArrow","L GUI+L Shift"
"1","7.0","2.0","Win+Left","Key Press","Keyboard LeftArrow","L GUI"
"1","8","2","↓","Key Press","DownArrow",""
"1","9.0","2.0","Ctrl+Shift+Enter","Key Press","Keyboard Return Enter","L Ctrl+L Shift"
"1","10.0","2.0","Alt+Down","Key Press","Keyboard DownArrow","L Alt"
"1","11.0","2.0","F11","Key Press","Keyboard F11",""
"1","12.0","2.0","Ctrl+L","Key Press","Keyboard L","L Ctrl"
"1","0.0","3.0","Ctrl+O","Key Press","Keyboard O","L Ctrl"
"1","1.0","3.0","Ctrl+Shift+V","Key Press","Keyboard V","L Ctrl+L Shift"
"1","2.0","3.0","Ctrl+Shift+!","Key Press","Keyboard 1 and Bang","L Ctrl+L Shift"
"1","3.0","3.0","Shift+Alt+A","Key Press","Keyboard A","L Shift+L Alt"
"1","4.0","3.0","Ctrl+Shift+6","Key Press","Keyboard 6 and Caret","L Ctrl+L Shift"
"1","5.0","3.0","Ctrl+Shift+U","Key Press","Keyboard U","L Ctrl+L Shift"
"1","7.0","3.0","F8","Key Press","Keyboard F8",""
"1","8.0","3.0","Shift+Tab","Key Press","Keyboard Tab","L Shift"
"1","9.0","3.0","Ctrl+Shift+L","Key Press","Keyboard L","L Ctrl+L Shift"
"1","10.0","3.0","Ctrl+Shift+A","Key Press","Keyboard A","L Ctrl+L Shift"
"1","11.0","3.0","H","Key Press","Keyboard H",""
"1","12.0","3.0","x","Key Press","Keyboard x",""
"1","3.0","4.0","Ctrl+Shift+W","Key Press","Keyboard W","L Ctrl+L Shift"
"1","4.0","4.0","Ctrl+Home","Key Press","Keyboard Home","L Ctrl"
"1","5.0","4.0","Ctrl+K","Key Press","Keyboard K","L Ctrl"
"1","7.0","4.0","Ctrl+S","Key Press","Keyboard S","L Ctrl"
"1","8.0","4.0","Ctrl+Shift+M","Key Press","Keyboard M","L Ctrl+L Shift"
"1","4.0","5.0","Ctrl+\","Key Press","Keyboard Backslash and Pipe","L Ctrl"
"1","5","5","Ctrl+-","Key Press","Dash and Underscore","L Ctrl"
"1","7.0","5.0","Ctrl+Shift+Right","Key Press","Keyboard RightArrow","L Ctrl+L Shift"
"2","0.0","0.0","Ctrl+Shift+Q","Key Press","Keyboard Q","L Ctrl+L Shift"
"2","1.0","0.0","Alt+=","Key Press","Keyboard Equals and Plus","L Alt"
"2","2.0","0.0","Win+C","Key Press","Keyboard C","L GUI"
"2","3.0","0.0","Ctrl+Shift+Tab","Key Press","Keyboard Tab","L Ctrl+L Shift"
"2","4.0","0.0","=","Key Press","Keyboard Equals and Plus",""
"2","5.0","0.0","Alt+Enter","Key Press","Keyboard Return Enter","L Alt"
"2","7.0","0.0","Alt+Shift+Up","Key Press","Keyboard UpArrow","L Alt+L Shift"
"2","8.0","0.0","Win+1","Key Press","Keyboard 1 and Bang","L GUI"
"2","9.0","0.0","Win+B","Key Press","Keyboard B","L GUI"
"2","10.0","0.0","Win+Ctrl+D","Key Press","Keyboard D","L GUI+L Ctrl"
"2","11.0","0.0","Ctrl+3","Key Press","Keyboard 3 and Hash","L Ctrl"
"2","12.0","0.0","Ctrl+Shift+G","Key Press","Keyboard G","L Ctrl+L Shift"
"2","0.0","1.0","Ctrl+B","Key Press","Keyboard B","L Ctrl"
"2","1.0","1.0","t","Key Press","Keyboard t",""
"2","2.0","1.0","Alt+Shift+-","Key Press","Keyboard Dash and Underscore","L Alt+L Shift"
"2","3.0","1.0","Ctrl+Down","Key Press","Keyboard DownArrow","L Ctrl"
"2","4.0","1.0","Shift+Alt+Left","Key Press","Keyboard LeftArrow","L Shift+L Alt"
"2","5.0","1.0","/","Key Press","Keyboard ForwardSlash and QuestionMark",""
"2","7.0","1.0","W","Key Press","Keyboard W",""
"2","8.0","1.0","X","Key Press","Keyboard X",""
"2","9.0","1.0","Win+E","Key Press","Keyboard E","L GUI"
"2","10.0","1.0","Shift+F8","Key Press","Keyboard F8","L Shift"
"2","11.0","1.0","Ctrl+Shift+~","Key Press","Keyboard Grave Accent and Tilde","L Ctrl+L Shift"
"2","12.0","1.0","Alt+Shift","Key Press","Keyboard Shift","L Alt"
"2","0.0","2.0","o","Key Press","Keyboard o",""
"2","1.0","2.0","B","Key Press","Keyboard B",""
"2","2.0","2.0","Alt+Shift++","Key Press","Keyboard Equals and Plus","L Alt+L Shift"
"2","3.0","2.0","Ctrl+I","Key Press","Keyboard I","L Ctrl"
"2","4.0","2.0","Ctrl+]","Key Press","Keyboard Right Brace","L Ctrl"
"2","5.0","2.0","Shift+Alt+Down","Key Press","Keyboard DownArrow","L Shift+L Alt"
"2","7.0","2.0","Ctrl+N","Key Press","Keyboard N","L Ctrl"
"2","8.0","2.0","Ctrl+Shift+Z","Key Press","Keyboard Z","L Ctrl+L Shift"
"2","9.0","2.0","Win+R","Key Press","Keyboard R","L GUI"
"2","10.0","2.0","Shift+Delete","Key Press","Keyboard Delete","L Shift"
"2","11.0","2.0","Alt+Up","Key Press","Keyboard UpArrow","L Alt"
"2","12.0","2.0","Ctrl+F5","Key Press","Keyboard F5","L Ctrl"
"2","0.0","3.0","Win+V","Key Press","Keyboard V","L GUI"
"2","1.0","3.0","Win+;","Key Press","Keyboard SemiColon and Colon","L GUI"
"2","2.0","3.0","Win+Ctrl+F4","Key Press","Keyboard F4","L GUI+L Ctrl"
"2","3.0","3.0","Ctrl+/","Key Press","Keyboard ForwardSlash and QuestionMark","L Ctrl"
"2","4.0","3.0","Ctrl+K Ctrl+F","Key Press","Keyboard F","L Ctrl"
"2","5.0","3.0","Ctrl+End","Key Press","Keyboard End","L Ctrl"
"2","7.0","3.0","Ctrl+K Ctrl+S","Key Press","Keyboard S","L Ctrl"
"2","8.0","3.0","Ctrl+Alt+Up","Key Press","Keyboard UpArrow","L Ctrl+L Alt"
"2","9.0","3.0","Ctrl+X","Key Press","Keyboard X","L Ctrl"
"2","10.0","3.0","Ctrl+Shift+F6","Key Press","Keyboard F6","L Ctrl+L Shift"
"2","11.0","3.0","Alt+F4","Key Press","Keyboard F4","L Alt"
"2","12.0","3.0","Shift+F3","Key Press","Keyboard F3","L Shift"
"2","3.0","4.0","Down","Key Press","Keyboard DownArrow",""
"2","4.0","4.0","Win+Ctrl+Left","Key Press","Keyboard LeftArrow","L GUI+L Ctrl"
"2","5.0","4.0","Ctrl+Click","Key Press","Keyboard Click","L Ctrl"
"2","7.0","4.0","Ctrl+[","Key Press","Keyboard Left Brace","L Ctrl"
"2","8.0","4.0","Ctrl+Shift+T","Key Press","Keyboard T","L Ctrl+L Shift"
"2","4.0","5.0","Backspace","Key Press","Keyboard Delete",""
"2","5.0","5.0","Ctrl+T","Key Press","Keyboard T","L Ctrl"
"2","7.0","5.0","Ctrl+Shift+S","Key Press","Keyboard S","L Ctrl+L Shift"
"3","0.0","0.0","Ctrl+Shift+$","Key Press","Keyboard 4 and Dollar","L Ctrl+L Shift"
"3","1.0","0.0","gg","Key Press","Keyboard gg",""
"3","2.0","0.0","Shift+F11","Key Press","Keyboard F11","L Shift"
"3","3.0","0.0","F7","Key Press","Keyboard F7",""
"3","4.0","0.0","gi","Key Press","Keyboard gi",""
"3","5.0","0.0","Win+2","Key Press","Keyboard 2 and At","L GUI"
"3","7.0","0.0","Ctrl+Shift+Down","Key Press","Keyboard DownArrow","L Ctrl+L Shift"
"3","8.0","0.0","Alt+Tab","Key Press","Keyboard Tab","L Alt"
"3","9.0","0.0","Win+M","Key Press","Keyboard M","L GUI"
"3","10.0","0.0","Ctrl+9","Key Press","Keyboard 9 and Left Bracket","L Ctrl"
"3","11.0","0.0","Ctrl+Shift++","Key Press","Keyboard Equals and Plus","L Ctrl+L Shift"
"3","0.0","1.0","Ctrl+Alt+Down","Key Press","Keyboard DownArrow","L Ctrl+L Alt"
"3","1.0","1.0","Ctrl++","Key Press","Keyboard Equals and Plus","L Ctrl"
"3","2.0","1.0","Ctrl+F","Key Press","Keyboard F","L Ctrl"
"3","3.0","1.0","Ctrl+.","Key Press","Keyboard Period and GreaterThan","L Ctrl"
"3","4.0","1.0","Ctrl+M","Key Press","Keyboard M","L Ctrl"
"3","5.0","1.0","Ctrl+A","Key Press","Keyboard A","L Ctrl"
"3","7.0","1.0","Ctrl+-","Key Press","Keyboard Dash and Underscore","L Ctrl"
"3","8.0","1.0","Win+D","Key Press","Keyboard D","L GUI"
"3","9.0","1.0","Ctrl+Space","Key Press","Keyboard Spacebar","L Ctrl"
"3","10.0","1.0","F5","Key Press","Keyboard F5",""
"3","11.0","1.0","N","Key Press","Keyboard N",""
"3","12.0","1.0","Ctrl+Shift+F5","Key Press","Keyboard F5","L Ctrl+L Shift"
"3","0.0","2.0","Ctrl+Tab","Key Press","Keyboard Tab","L Ctrl"
"3","1.0","2.0","Win+I","Key Press","Keyboard I","L GUI"
"3","2.0","2.0","Up","Key Press","Keyboard UpArrow",""
"3","3.0","2.0","Ctrl+4","Key Press","Keyboard 4 and Dollar","L Ctrl"
"3","4.0","2.0","Win+.","Key Press","Keyboard Period and GreaterThan","L GUI"
"3","5.0","2.0","X","Key Press","Keyboard X",""
"3","7.0","2.0","Escape","Key Press","Keyboard Escape",""
"3","8.0","2.0","u","Key Press","Keyboard u",""
"3","9.0","2.0","Ctrl+Shift+Esc","Key Press","Keyboard Escape","L Ctrl+L Shift"
"3","10.0","2.0","Win+T","Key Press","Keyboard T","L GUI"
"3","11.0","2.0","F","Key Press","Keyboard F",""
"3","12.0","2.0","Ctrl+6","Key Press","Keyboard 6 and Caret","L Ctrl"
"3","0.0","3.0","n","Key Press","Keyboard n",""
"3","1.0","3.0","Ctrl+Shift+;","Key Press","Keyboard SemiColon and Colon","L Ctrl+L Shift"
"3","2.0","3.0","F10","Key Press","Keyboard F10",""
"3","3.0","3.0","Win+Down","Key Press","Keyboard DownArrow","L GUI"
"3","4.0","3.0","Win+K","Key Press","Keyboard K","L GUI"
"3","5.0","3.0","Ctrl+Shift+%","Key Press","Keyboard 5 and Percent","L Ctrl+L Shift"
"3","7.0","3.0","Ctrl+W","Key Press","Keyboard W","L Ctrl"
"3","8.0","3.0","Ctrl+K Ctrl+W","Key Press","Keyboard W","L Ctrl"
"3","9.0","3.0","Ctrl+Shift+I","Key Press","Keyboard I","L Ctrl+L Shift"
"3","10.0","3.0","G","Key Press","Keyboard G",""
"3","11.0","3.0","Ctrl+Shift+P","Key Press","Keyboard P","L Ctrl+L Shift"
"3","12.0","3.0","Ctrl+Shift+N","Key Press","Keyboard N","L Ctrl+L Shift"
"3","3.0","4.0","Ctrl+Enter","Key Press","Keyboard Return Enter","L Ctrl"
"3","4.0","4.0","Ctrl+Shift+`","Key Press","Keyboard Grave Accent and Tilde","L Ctrl+L Shift"
"3","5.0","4.0","Ctrl+Shift+X","Key Press","Keyboard X","L Ctrl+L Shift"
"3","7.0","4.0","Ctrl+Shift+K","Key Press","Keyboard K","L Ctrl+L Shift"
"3","8.0","4.0","Ctrl+Page Up","Key Press","Keyboard Page Up","L Ctrl"
"3","4.0","5.0","Ctrl+G","Key Press","Keyboard G","L Ctrl"
"3","5.0","5.0","Alt+P","Key Press","Keyboard P","L Alt"
"3","7.0","5.0","Ctrl+Q","Key Press","Keyboard Q","L Ctrl"
"4","0.0","0.0","Ctrl+7","Key Press","Keyboard 7 and Ampersand","L Ctrl"
"4","1.0","0.0","Alt+D","Key Press","Keyboard D","L Alt"
"4","2.0","0.0","d","Key Press","Keyboard d",""
"4","3.0","0.0","L","Key Press","Keyboard L",""
"4","4.0","0.0","Delete","Key Press","Keyboard Delete",""
"4","5.0","0.0","Ctrl+Shift+Del","Key Press","Keyboard Del","L Ctrl+L Shift"
"4","7.0","0.0","Page Up","Key Press","Keyboard Page Up",""
"4","8.0","0.0","Ctrl+Shift+1","Key Press","Keyboard 1 and Bang","L Ctrl+L Shift"
"4","9.0","0.0","Alt+F12","Key Press","Keyboard F12","L Alt"
"4","10.0","0.0","Ctrl+Shift+End","Key Press","Keyboard End","L Ctrl+L Shift"
"4","11.0","0.0","Ctrl+2","Key Press","Keyboard 2 and At","L Ctrl"
"4","12.0","0.0","P","Key Press","Keyboard P",""
"4","0.0","1.0","Ctrl+E","Key Press","Keyboard E","L Ctrl"
"4","1.0","1.0","Ctrl+K S","Key Press","Keyboard K S","L Ctrl"
"4","2.0","1.0","Ctrl+C","Key Press","Keyboard C","L Ctrl"
"4","3.0","1.0","Ctrl+;","Key Press","Keyboard SemiColon and Colon","L Ctrl"
"4","4.0","1.0","?","Key Press","Keyboard ForwardSlash and QuestionMark",""
"4","5.0","1.0","Win+L","Key Press","Keyboard L","L GUI"
"4","7.0","1.0","Ctrl+Shift+R","Key Press","Keyboard R","L Ctrl+L Shift"
"4","8.0","1.0","Alt+Shift+Down","Key Press","Keyboard DownArrow","L Alt+L Shift"
"4","10.0","1.0","Shift+Alt+Up","Key Press","Keyboard UpArrow","L Shift+L Alt"
"4","11.0","1.0","Win+Right","Key Press","Keyboard RightArrow","L GUI"
"4","12.0","1.0","Alt+Click","Key Press","Keyboard Click","L Alt"
"4","0.0","2.0","Ctrl+Shift+B","Key Press","Keyboard B","L Ctrl+L Shift"
"4","1.0","2.0","Win+Space","Key Press","Keyboard Spacebar","L GUI"
"4","2.0","2.0","Shift+Space","Key Press","Keyboard Spacebar","L Shift"
"4","3.0","2.0","F12","Key Press","Keyboard F12",""
"4","4.0","2.0","F1","Key Press","Keyboard F1",""
"4","5.0","2.0","Win+X","Key Press","Keyboard X","L GUI"
"4","7.0","2.0","Ctrl+F6","Key Press","Keyboard F6","L Ctrl"
"4","8.0","2.0","Ctrl+Shift+H","Key Press","Keyboard H","L Ctrl+L Shift"
"4","9.0","2.0","Ctrl+Right","Key Press","Keyboard RightArrow","L Ctrl"
"4","10.0","2.0","Ctrl+8","Key Press","Keyboard 8 and Star","L Ctrl"
"4","11.0","2.0","Ctrl+Shift+E","Key Press","Keyboard E","L Ctrl+L Shift"
"4","12.0","2.0","Win+N","Key Press","Keyboard N","L GUI"
"4","0.0","3.0","Ctrl+R","Key Press","Keyboard R","L Ctrl"
"4","1.0","3.0","Win+3","Key Press","Keyboard 3 and Hash","L GUI"
"4","2.0","3.0","Shift+F5","Key Press","Keyboard F5","L Shift"
"4","3.0","3.0","Ctrl+Shift+Up","Key Press","Keyboard UpArrow","L Ctrl+L Shift"
"4","4.0","3.0","J","Key Press","Keyboard J",""
"4","5.0","3.0","j","Key Press","Keyboard j",""
"4","7.0","3.0","Win+Ctrl+Right","Key Press","Keyboard RightArrow","L GUI+L Ctrl"
"4","8.0","3.0","Ctrl+U","Key Press","Keyboard U","L Ctrl"
"4","9.0","3.0","Ctrl+Page Down","Key Press","Keyboard Page Down","L Ctrl"
"4","10.0","3.0","Shift+Enter","Key Press","Keyboard Return Enter","L Shift"
"4","11.0","3.0","Win+Pause","Key Press","Keyboard Pause","L GUI"
"4","12.0","3.0","Space","Key Press","Keyboard Spacebar",""
"4","3.0","4.0","Ctrl+Shift+O","Key Press","Keyboard O","L Ctrl+L Shift"
"4","4.0","4.0","Ctrl+`","Key Press","Keyboard Grave Accent and Tilde","L Ctrl"
"4","5.0","4.0","Win+5","Key Press","Keyboard 5 and Percent","L GUI"
"4","7.0","4.0","Alt+Home","Key Press","Keyboard Home","L Alt"
"4","8.0","4.0","Ctrl+Shift+<","Key Press","Keyboard Comma and LessThan","L Ctrl+L Shift"
"4","4.0","5.0","Ctrl+Shift+Home","Key Press","Keyboard Home","L Ctrl+L Shift"
"4","5.0","5.0","Ctrl+Shift+9","Key Press","Keyboard 9 and Left Bracket","L Ctrl+L Shift"
"4","7.0","5.0","Ctrl+V","Key Press","Keyboard V","L Ctrl"
"5","0.0","0.0","f","Key Press","Keyboard f",""
"5","1.0","0.0","Win+Tab","Key Press","Keyboard Tab","L GUI"
"5","2.0","0.0","Alt+Left","Key Press","Keyboard LeftArrow","L Alt"
"5","3.0","0.0","Ctrl+P","Key Press","Keyboard P","L Ctrl"
"5","4.0","0.0","Ctrl+Y","Key Press","Keyboard Y","L Ctrl"
"5","5.0","0.0","F2","Key Press","Keyboard F2",""
"5","7","0","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"5","8","0","Ctrl+G","Key Press","G","L Ctrl"
"5","9.0","0.0","Shift+Alt+Right","Key Press","Keyboard RightArrow","L Shift+L Alt"
"5","10","0","Explr","Key Press","E","L Ctrl+L Shift"
"5","0","1","Wrap","Key Press","Z","L Alt"
"5","1","1","Ctrl+Shift+F","Key Press","F","L Ctrl+L Shift"
"5","2","1","f18","Key Press","F18",""
"5","3","1","Win+Ctrl+Right","Key Press","RightArrow","L Ctrl+L GUI"
"5","4","1","InsUp","Key Press","Return Enter","L Ctrl+L Shift"
"5","5","1","Ctrl+Shift+`","Key Press","Grave Accent and Tilde","L Ctrl+L Shift"
"5","9","1","Ctrl+W","Key Press","W","L Ctrl"
"5","10","1","f1","Key Press","F1",""
"5","11","1","backslash","Key Press","Backslash and Pipe",""
"5","0","2","Ctrl+N","Key Press","N","L Ctrl"
"5","1","2","Save","Key Press","S","L Ctrl"
"5","2","2","Ctrl+J","Key Press","J","L Ctrl"
"5","3","2","Sett","Key Press","Comma and LessThan","L Ctrl"
"5","4","2","DelLn","Key Press","K","L Ctrl+L Shift"
"5","5","2","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"5","9","2","Ctrl+L","Key Press","L","L Ctrl"
"5","11.0","2.0","Shift+Click","Key Press","Keyboard Click","L Shift"
"5","1","3","PstNF","Key Press","V","L Ctrl+L Shift"
"5","3","3","NTerm","Key Press","Grave Accent and Tilde","L Ctrl+L Shift"
"5","4","3","Ext","Key Press","X","L Ctrl+L Shift"
"5","5","3","f8","Key Press","F8",""
"5","10","3","keypad 3","Key Press","3 and PageDn",""
"5","3","4","Base","coach_base","",""
"6","3","0","Alt+=","Key Press","Equals and Plus","L Alt"
"6","4","0","Ctrl+Left","Key Press","LeftArrow","L Ctrl"
"6","8","0","Ctrl+Q","Key Press","Q","L Ctrl"
"6","2","1","Ctrl+Space","Key Press","Spacebar","L Ctrl"
"6","3","1","F10","Key Press","F10",""
"6","4","1","Win+Shift+Left","Key Press","LeftArrow","L GUI+L Shift"
"6","5","1","Ctrl+Right","Key Press","RightArrow","L Ctrl"
"6","7","1","Ctrl+Shift+R","Key Press","R","L Ctrl+L Shift"
"6","8","1","Alt+Right","Key Press","RightArrow","L Alt"
"6","9","1","Ctrl+5","Key Press","5 and Percent","L Ctrl"
"6","10","1","Ctrl+Shift+Left","Key Press","LeftArrow","L Ctrl+L Shift"
"6","1","2","Ctrl+Shift+Down","Key Press","DownArrow","L Ctrl+L Shift"
"6","2","2","F9","Key Press","F9",""
"6","4","2","Ctrl+3","Key Press","3 and Hash","L Ctrl"
"6","5","2","Win+Space","Key Press","Spacebar","L GUI"
"6","8","2","Ctrl+4","Key Press","4 and Dollar","L Ctrl"
"6","9","2","F5","Key Press","F5",""
"6","10","2","Ctrl+Alt+Down","Key Press","DownArrow","L Alt+L Ctrl"
"6","11","2","Ctrl+Shift+Up","Key Press","UpArrow","L Ctrl+L Shift"
"6","2","3","Ctrl+Shift++","Key Press","Equals and Plus","L Ctrl+L Shift"
"6","3","3","Shift+F11","Key Press","F11","L Shift"
"6","4","3","Win+Shift+Right","Key Press","RightArrow","L GUI+L Shift"
"6","5","3","F4","Key Press","F4",""
"6","7","3","Ctrl+Shift+I","Key Press","I","L Ctrl+L Shift"
"6","8","3","Ctrl+Shift+T","Key Press","T","L Ctrl+L Shift"
"6","9","3","Ctrl+6","Key Press","6 and Caret","L Ctrl"
"6","10","3","Ctrl+Shift+Right","Key Press","RightArrow","L Ctrl+L Shift"
"6","4","4","Ctrl+0","Key Press","0 and Right Bracket","L Ctrl"
"7","1","1","9 PU","Key Press","9 and PageUp",""
"7","2","1","↑","Key Press","UpArrow",""
"7","3","1","3 PD","Key Press","3 and PageDn",""
"7","9","1","3 PD","Key Press","3 and PageDn",""
"7","10","1","↑","Key Press","UpArrow",""
"7","11","1","9 PU","Key Press","9 and PageUp",""
"7","1","2","←","Key Press","LeftArrow",""
"7","2","2","↓","Key Press","DownArrow",""
"7","3","2","→","Key Press","RightArrow",""
"7","4","2","Z","Key Press","Z",""
"7","8","2","Z","Key Press","Z",""
"7","9","2","←","Key Press","LeftArrow",""
"7","10","2","↓","Key Press","DownArrow",""
"7","11","2","→","Key Press","RightArrow",""
"7","1","3","X","Key Press","X",""
"7","2","3","C","Key Press","C",""
"7","3","3","Shft","Key Press","LeftShift",""
"7","4","3","Esc","Key Press","Escape",""
"7","8","3","Esc","Key Press","Escape",""
"7","9","3","Shft","Key Press","LeftShift",""
"7","10","3","C","Key Press","C",""
"7","11","3","X","Key Press","X",""
"7","3","4","Exit Base","coach_base","",""
"7","4","4","␣","Key Press","Spacebar",""
"7","5","4","Exit Base","coach_base","",""
"7","7","4","Exit Base","coach_base","",""
"7","8","4","Exit Base","coach_base","",""
"7","4","5","Click","Mouse Key Press","default_transform",""
"7","5","5","Right Click","Mouse Key Press","default_transform",""
"7","7","5","Ret","Key Press","Return Enter",""
"8","4","0","escape","Key Press","Escape",""
"8","8","0","Shift+Space","Key Press","Spacebar","L Shift"
"8","2","1","F11","Key Press","F11",""
"8","3","1","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"8","4","1","home","Key Press","Home",""
"8","5","1","Win+Ctrl+Right","Key Press","RightArrow","L Ctrl+L GUI"
"8","7","1","Ctrl+Shift+Esc","Key Press","Escape","L Ctrl+L Shift"
"8","8","1","Ctrl+Shift+Z","Key Press","Z","L Ctrl+L Shift"
"8","9","1","Ctrl+-","Key Press","Dash and Underscore","L Ctrl"
"8","2","2","Ctrl+Shift+F6","Key Press","F6","L Ctrl+L Shift"
"8","4","2","left gui","Key Press","Left GUI",""
"8","7","2","Ctrl+Shift+`","Key Press","Grave Accent and Tilde","L Ctrl+L Shift"
"8","8","2","Alt+F4","Key Press","F4","L Alt"
"8","9","2","Alt+Down","Key Press","DownArrow","L Alt"
"8","10","2","Ctrl+.","Key Press","Period and GreaterThan","L Ctrl"
"8","3.0","3.0","Escape","Key Press","Keyboard Escape",""
"8","4","3","tab","Key Press","Tab",""
"8","5","3","Win+.","Key Press","Period and GreaterThan","L GUI"
"8","7","3","Win+;","Key Press","SemiColon and Colon","L GUI"
"8","8","3","Alt+Up","Key Press","UpArrow","L Alt"
"8","9","3","Ctrl+Home","Key Press","Home","L Ctrl"
"8","7","4","Exit Travel","coach_travel_off","",""
"8","4","5","Delete","Key Press","Delete",""
"8","5","5","F10","Key Press","F10",""
"9","4","0","Ctrl+End","Key Press","End","L Ctrl"
"9","8","0","Ctrl+Up","Key Press","UpArrow","L Ctrl"
"9","0","1","f2","Key Press","F2",""
"9","1","1","WfSt","Key Press","W","L Ctrl+L Shift"
"9","2","1","Asgn","Key Press","A","L Ctrl+L Shift"
"9","4","1","Fav","Key Press","M","L Ctrl"
"9","5.0","1.0","Ctrl+1","Key Press","Keyboard 1 and Bang","L Ctrl"
"9","7","1","Print","Key Press","P","L Ctrl"
"9","8","1","Shift+Alt+Down","Key Press","DownArrow","L Alt+L Shift"
"9","0","2","pageup","Key Press","9 and PageUp",""
"9","1","2","Save","Key Press","S","L Ctrl"
"9","2","2","ChkIn","Key Press","E","L Ctrl+L Shift"
"9","4","2","Win+Tab","Key Press","Tab","L GUI"
"9","5","2","Icon","Key Press","2 and At","L Ctrl"
"9","8","2","leftshift","Key Press","LeftShift",""
"9","10","2","Hist","Key Press","H","L Ctrl+L Shift"
"9","11","2","Rel","Key Press","K","L Ctrl"
"9","12","2","UndCO","Key Press","U","L Ctrl+L Shift"
"9","1","3","DLoad","Key Press","D","L Ctrl+L Shift"
"9","2","3","Open","Key Press","O","L Ctrl"
"9","3","3","CpLnk","Key Press","C","L Ctrl+L Shift"
"9","4","3","Notif","Key Press","F5","L Ctrl+L Shift"
"9","5","3","Group","Key Press","G","L Ctrl+L Shift"
"9","7","3","Vault","Key Press","G","L Ctrl"
"9","8","3","rightarrow_combo","Key Press","RightArrow",""
"9","9","3","Ctrl+Down","Key Press","DownArrow","L Ctrl"
"10","0","0","ShftEnt","Key Press","Return Enter","L Shift"
"10","1.0","0.0","K","Key Press","Keyboard K",""
"10","2","0","Copy","Key Press","C","L Ctrl"
"10","3","0","Cut","Key Press","X","L Ctrl"
"10","4","0","AutoSum","Key Press","Equals and Plus","L Alt"
"10","10","0","Ctrl+Dn","Key Press","DownArrow","L Ctrl"
"10","12.0","0.0","Escape","Key Press","Keyboard Escape",""
"10","0","1","ShftTab","Key Press","Tab","L Shift"
"10","1","1","Sel←","Key Press","LeftArrow","L Ctrl+L Shift"
"10","3","1","Sel↑","Key Press","UpArrow","L Ctrl+L Shift"
"10","5","1","InsTime","Key Press","SemiColon and Colon","L Ctrl+L Shift"
"10","8","1","coach_mouse_lock","coach_mouse_lock","",""
"10","10","1","SelHome","Key Press","Home","L Ctrl+L Shift"
"10","11","1","Win+B","Key Press","B","L GUI"
"10","12","1","coach_game_lock","coach_game_lock","",""
"10","0","2","Find","Key Press","F","L Ctrl"
"10","1","2","SelCol","Key Press","Spacebar","L Ctrl"
"10","2","2","F4 $Ref","Key Press","F4",""
"10","4","2","SelEnd","Key Press","End","L Ctrl+L Shift"
"10","7","2","Win+L","Key Press","L","L GUI"
"10","8","2","Paste","Key Press","V","L Ctrl"
"10","9","2","NextSht","Key Press","PageDown","L Ctrl"
"10","10","2","Undo","Key Press","Z","L Ctrl"
"10","11","2","Win+2","Key Press","2 and At","L GUI"
"10","12","2","Win+N","Key Press","N","L GUI"
"10","0","3","HideRow","Key Press","9 and Left Bracket","L Ctrl"
"10","1","3","Replace","Key Press","H","L Ctrl"
"10","2","3","Delete","Key Press","Dash and Underscore","L Ctrl"
"10","3","3","NumFmt","Key Press","1 and Bang","L Ctrl+L Shift"
"10","4","3","Ctrl+Alt+Up","Key Press","UpArrow","L Alt+L Ctrl"
"10","5.0","3.0","Alt+Right","Key Press","Keyboard RightArrow","L Alt"
"10","8","3","Win+E","Key Press","E","L GUI"
"10","10","3","grave accent_combo","Key Press","Grave Accent and Tilde",""
"10","11","3","Win+Left","Key Press","LeftArrow","L GUI"
"10","3","4","Base","coach_base","",""
"10","4","4","f13","Key Press","F13",""
"10","7","4","Win+T","Key Press","T","L GUI"
"10","7","5","Win+Ctrl+D","Key Press","D","L Ctrl+L GUI"
`;

function parseExpected() {
  const lines = EXPECTED_CSV.trim().split('\n');
  const headers = lines[0].split(',').map(h => h.split(String.fromCharCode(34)).join('').trim());
  const out = [];
  for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split(',').map(p => p.split(String.fromCharCode(34)).join('').trim());
    const obj = {};
    for (let j = 0; j < headers.length; j++) obj[headers[j]] = parts[j] || '';
    out.push(obj);
  }
  return out;
}

function runVerify() {
  const expected = parseExpected();
  let pass = 0, fail = 0, errors = [];
  for (const exp of expected) {
    const layer = parseInt(exp.layer);
    const x = parseInt(exp.x);
    const y = parseInt(exp.y);
    const actual = getKeyBinding(layer, x, y);
    if (!actual) {
      fail++;
      errors.push({layer, x, y, expected: exp, error: 'key not found'});
      continue;
    }
    const bMatch = actual.behavior.toLowerCase() === exp.behavior.toLowerCase();
    const pMatch = actual.parameter.toLowerCase() === exp.parameter.toLowerCase();
    const mMatch = actual.modifiers === exp.modifiers;
    if (bMatch && pMatch && mMatch) {
      pass++;
    } else {
      fail++;
      errors.push({layer, x, y, expected: exp, actual});
    }
  }
  console.log('Verify result: ' + pass + ' pass, ' + fail + ' fail (' + (pass/(pass+fail)*100).toFixed(1) + '%)');
  window._CHARYBDIS_VERIFY_RESULT = {pass, fail, errors};
}

runVerify();