// ZMK Studio verify script for evolved V2 layout
window.CHARYBDIS_VERSION = "evolved-v2";

function getKeyBinding(layer, x, y) {
  const btn = document.querySelector(`[data-layer='${layer}'][data-x='${x}'][data-y='${y}']`);
  if (!btn) return null;
  const behavior = btn.querySelector('.behavior-name')?.textContent?.trim() || '';
  const parameter = btn.querySelector('.parameter-name')?.textContent?.trim() || '';
  const modifiers = Array.from(btn.querySelectorAll('.modifier-tag')).map(m => m.textContent.trim()).join('+');
  return {behavior, parameter, modifiers};
}

const EXPECTED_CSV = `"layer","x","y","label","behavior","parameter","modifiers"
"0","0","0","Esc","Key Press","Escape",""
"0","1","0","1","Key Press","1 and Bang",""
"0","2","0","2","Key Press","2 and At",""
"0","3","0","3","Key Press","3 and Hash",""
"0","4","0","4","Key Press","4 and Dollar",""
"0","5","0","5","Key Press","5 and Percent",""
"0","7","0","6","Key Press","6 and Caret",""
"0","8","0","7","Key Press","7 and Ampersand",""
"0","9","0","8","Key Press","8 and Star",""
"0","10","0","9","Key Press","9 and Left Bracket",""
"0","11","0","0","Key Press","0 and Right Bracket",""
"0","12","0","BkSp","Key Press","Delete",""
"0","0","1","Tab","Key Press","Tab",""
"0","1","1","Q","Key Press","Q",""
"0","2","1","W","Key Press","W",""
"0","3","1","E","Key Press","E",""
"0","4","1","R","Key Press","R",""
"0","5","1","T","Key Press","T",""
"0","7","1","Y","Key Press","Y",""
"0","8","1","U","Key Press","U",""
"0","9","1","I","Key Press","I",""
"0","10","1","O","Key Press","O",""
"0","11","1","P","Key Press","P",""
"0","12","1","å","Key Press","Left Brace",""
"0","0","2","Shft","Key Press","LeftShift",""
"0","1","2","A","Key Press","A",""
"0","2","2","S","Key Press","S",""
"0","3","2","D","Key Press","D",""
"0","4","2","F","Key Press","F",""
"0","5","2","G","Key Press","G",""
"0","7","2","H","Key Press","H",""
"0","8","2","J","Key Press","J",""
"0","9","2","K","Key Press","K",""
"0","10","2","L","Key Press","L",""
"0","11","2","ø","Key Press","SemiColon and Colon",""
"0","12","2","æ","Key Press","Left Apos and Double",""
"0","0","3","Ctrl","Key Press","LeftControl",""
"0","1","3","Z","Key Press","Z",""
"0","2","3","X","Key Press","X",""
"0","3","3","C","Key Press","C",""
"0","4","3","V","Key Press","V",""
"0","5","3","B","Key Press","B",""
"0","7","3","N","Key Press","N",""
"0","8","3","M","Key Press","M",""
"0","9","3",",","Key Press","Comma and LessThan",""
"0","10","3",".","Key Press","Period and GreaterThan",""
"0","11","3","/","Key Press","ForwardSlash and QuestionMark",""
"0","12","3","\","Key Press","Backslash and Pipe",""
"0","3","4","Nav","coach_l1_hold","",""
"0","4","4","␣","Key Press","Spacebar",""
"0","5","4","Speed","coach_travel_toggle","",""
"0","7","4","System","coach_l4_hold","",""
"0","8","4","Window","coach_l3_hold","",""
"0","5","5","Mouse","coach_l2_hold","",""
"0","7","5","Ret","Key Press","Return Enter",""
"1","0","0","Dash and Underscore","Key Press","Dash and Underscore",""
"1","1","0","=","Key Press","Equals and Plus",""
"1","2","0","Grave Accent and Tilde","Key Press","Grave Accent and Tilde",""
"1","3","0","Right Brace","Key Press","Right Brace",""
"1","4","0","Page Up","Key Press","PageUp",""
"1","5","0","Page Down","Key Press","PageDown",""
"1","7","0","Home","Key Press","Home",""
"1","8","0","End","Key Press","End",""
"1","11","0","Ctrl+Shift+Left","Key Press","LeftArrow","L Ctrl+L Shift"
"1","0","1","Code","Toggle Layer","Layer::5",""
"1","1","1","Alt+F12","Key Press","F12","L Alt"
"1","3","1","Ctrl+Shift+W","Key Press","W","L Ctrl+L Shift"
"1","4","1","Win+Shift+S","Key Press","S","L GUI+L Shift"
"1","5","1","Ctrl+V","Key Press","V","L Ctrl"
"1","7","1","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"1","8","1","Shift+F8","Key Press","F8","L Shift"
"1","9","1","Shift+F11","Key Press","F11","L Shift"
"1","10","1","Ctrl+Shift+A","Key Press","A","L Ctrl+L Shift"
"1","11","1","Ctrl+Shift+Up","Key Press","UpArrow","L Ctrl+L Shift"
"1","12","1","Ctrl+P","Key Press","P","L Ctrl"
"1","0","2","Ctrl+G","Key Press","G","L Ctrl"
"1","2","2","Alt+Left","Key Press","LeftArrow","L Alt"
"1","3","2","Scroll","Momentary Layer","Layer::6",""
"1","4","2","Ctrl+E","Key Press","E","L Ctrl"
"1","5","2","F2","Key Press","F2",""
"1","7","2","Win+S","Key Press","S","L GUI"
"1","9","2","Ctrl+1","Key Press","1 and Bang","L Ctrl"
"1","10","2","F9","Key Press","F9",""
"1","11","2","Ctrl+End","Key Press","End","L Ctrl"
"1","12","2","Ctrl+Page Down","Key Press","PageDown","L Ctrl"
"1","2","3","F5","Key Press","F5",""
"1","3","3","Excel","Toggle Layer","Layer::10",""
"1","5","3","coach_base","coach_base","",""
"1","7","3","Ctrl+C","Key Press","C","L Ctrl"
"1","8","3","Ctrl+Shift+G","Key Press","G","L Ctrl+L Shift"
"1","3","4","Win+N","Key Press","N","L GUI"
"1","4","4","coach_travel_toggle","coach_travel_toggle","",""
"1","5","4","Ctrl+Enter","Key Press","Return Enter","L Ctrl"
"1","7","4","Ctrl+2","Key Press","2 and At","L Ctrl"
"1","8","4","Ctrl+P","Key Press","P","L Ctrl"
"1","4","5","Ctrl+Page Up","Key Press","PageUp","L Ctrl"
"1","7","5","Ctrl+Shift++","Key Press","Equals and Plus","L Ctrl+L Shift"
"2","0","0","Ctrl+C","Key Press","C","L Ctrl"
"2","2","0","Ctrl+R","Key Press","R","L Ctrl"
"2","3","0","F10","Key Press","F10",""
"2","4","0","Ctrl+Shift+G","Key Press","G","L Ctrl+L Shift"
"2","5","0","Ctrl+Click","Mouse Key Press","MB1","L Ctrl"
"2","8","0","Ctrl+2","Key Press","2 and At","L Ctrl"
"2","10","0","Ctrl+F","Key Press","F","L Ctrl"
"2","0","1","Win+E","Key Press","E","L GUI"
"2","1","1","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"2","2","1","Ctrl+W","Key Press","W","L Ctrl"
"2","3","1","Win+B","Key Press","B","L GUI"
"2","4","1","F5","Key Press","F5",""
"2","7","1","Alt+Shift+Up","Key Press","UpArrow","L Alt+L Shift"
"2","9","1","F4","Key Press","F4",""
"2","10","1","Alt+Shift+Down","Key Press","DownArrow","L Alt+L Shift"
"2","11","1","Ctrl+I","Key Press","I","L Ctrl"
"2","12","1","Ctrl+X","Key Press","X","L Ctrl"
"2","1","2","Ctrl+H","Key Press","H","L Ctrl"
"2","2","2","Ctrl+1","Key Press","1 and Bang","L Ctrl"
"2","3","2","Ctrl+K","Key Press","K","L Ctrl"
"2","4","2","Ctrl+I","Key Press","I","L Ctrl"
"2","5","2","Ctrl+6","Key Press","6 and Caret","L Ctrl"
"2","7","2","Ctrl+Shift+F","Key Press","F","L Ctrl+L Shift"
"2","8","2","Ctrl+L","Key Press","L","L Ctrl"
"2","9","2","coach_travel_toggle","coach_travel_toggle","",""
"2","11","2","F5","Key Press","F5",""
"2","12","2","Ctrl+D","Key Press","D","L Ctrl"
"2","1","3","Ctrl+Shift+O","Key Press","O","L Ctrl+L Shift"
"2","2","3","Shift+Alt+A","Key Press","A","L Shift+L Alt"
"2","3","3","Scroll","Momentary Layer","Layer::6",""
"2","4","3","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"2","5","3","Ctrl+V","Key Press","V","L Ctrl"
"2","9","3","Ctrl+Shift+$","Key Press","4 and Dollar","L Ctrl+L Shift"
"2","10","3","Ctrl+Z","Key Press","Z","L Ctrl"
"2","3","4","DMS","Toggle Layer","Layer::9",""
"2","4","4","Exit Travel","coach_travel_off","",""
"2","4","5","coach_game_lock","coach_game_lock","",""
"2","5","5","Win+I","Key Press","I","L GUI"
"2","7","5","Ctrl+F5","Key Press","F5","L Ctrl"
"3","1","0","Win+3","Key Press","3 and Hash","L GUI"
"3","4","0","Win+A","Key Press","A","L GUI"
"3","5","0","Ctrl+Y","Key Press","Y","L Ctrl"
"3","7","0","Win+T","Key Press","T","L GUI"
"3","8","0","Ctrl+Q","Key Press","Q","L Ctrl"
"3","9","0","Ctrl+Shift+Down","Key Press","DownArrow","L Ctrl+L Shift"
"3","10","0","Alt+Shift+-","Key Press","Dash and Underscore","L Alt+L Shift"
"3","1","1","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"3","4","1","Win+M","Key Press","M","L GUI"
"3","8","1","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"3","9","1","Ctrl+S","Key Press","S","L Ctrl"
"3","11","1","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"3","12","1","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"3","1","2","Alt+D","Key Press","D","L Alt"
"3","2","2","Ctrl+G","Key Press","G","L Ctrl"
"3","3","2","Win+1","Key Press","1 and Bang","L GUI"
"3","4","2","Win+4","Key Press","4 and Dollar","L GUI"
"3","5","2","Win+5","Key Press","5 and Percent","L GUI"
"3","7","2","Win+S","Key Press","S","L GUI"
"3","8","2","Ctrl+End","Key Press","End","L Ctrl"
"3","11","2","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"3","12","2","Alt+Down","Key Press","DownArrow","L Alt"
"3","0","3","Ctrl+O","Key Press","O","L Ctrl"
"3","3","3","Win+H","Key Press","H","L GUI"
"3","4","3","Ctrl+Shift+Right","Key Press","RightArrow","L Ctrl+L Shift"
"3","5","3","Ctrl+Shift+Enter","Key Press","Return Enter","L Ctrl+L Shift"
"3","8","3","Win+N","Key Press","N","L GUI"
"3","10","3","Win+D","Key Press","D","L GUI"
"3","12","3","Ctrl+Shift+N","Key Press","N","L Ctrl+L Shift"
"3","3","4","Ctrl+Space","Key Press","Spacebar","L Ctrl"
"3","4","4","Ctrl+Shift+Z","Key Press","Z","L Ctrl+L Shift"
"3","5","4","Ctrl+`","Key Press","Grave Accent and Tilde","L Ctrl"
"3","7","4","Alt+Enter","Key Press","Return Enter","L Alt"
"3","8","4","Ctrl+Shift+W","Key Press","W","L Ctrl+L Shift"
"3","4","5","Ctrl++","Key Press","Equals and Plus","L Ctrl"
"3","5","5","Ctrl+-","Key Press","Dash and Underscore","L Ctrl"
"3","7","5","Ctrl+Shift+J","Key Press","J","L Ctrl+L Shift"
"4","2","0","Ctrl+3","Key Press","3 and Hash","L Ctrl"
"4","7","0","Ctrl+Shift+X","Key Press","X","L Ctrl+L Shift"
"4","11","0","Ctrl+G","Key Press","G","L Ctrl"
"4","0","1","Ctrl+G","Key Press","G","L Ctrl"
"4","1","1","Ctrl+O","Key Press","O","L Ctrl"
"4","7","1","Ctrl+Shift+Tab","Key Press","Tab","L Ctrl+L Shift"
"4","8","1","Ctrl+F","Key Press","F","L Ctrl"
"4","10","1","Ctrl+L","Key Press","L","L Ctrl"
"4","11","1","Ctrl+.","Key Press","Period and GreaterThan","L Ctrl"
"4","12","1","Ctrl+U","Key Press","U","L Ctrl"
"4","1","2","Alt+F","Key Press","F","L Alt"
"4","2","2","Ctrl+,","Key Press","Comma and LessThan","L Ctrl"
"4","3","2","Ctrl+\","Key Press","Backslash and Pipe","L Ctrl"
"4","4","2","Alt+Tab","Key Press","Tab","L Alt"
"4","7","2","Ctrl+U","Key Press","U","L Ctrl"
"4","10","2","F12","Key Press","F12",""
"4","11","2","F5","Key Press","F5",""
"4","12","2","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"4","2","3","Ctrl+Shift+M","Key Press","M","L Ctrl+L Shift"
"4","3","3","Scroll","Toggle Layer","Layer::6",""
"4","9","3","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"4","10","3","F4","Key Press","F4",""
"4","11","3","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"4","12","3","Ctrl+Shift+C","Key Press","C","L Ctrl+L Shift"
"4","4","4","Ctrl+T","Key Press","T","L Ctrl"
"4","5","4","F4","Key Press","F4",""
"4","7","4","MB4","Mouse Key Press","MB4",""
"4","8","4","F9","Key Press","F9",""
"4","4","5","Ctrl+[","Key Press","Left Brace","L Ctrl"
"4","5","5","Win+P","Key Press","P","L GUI"
"4","7","5","Ctrl+Shift+\","Key Press","Backslash and Pipe","L Ctrl+L Shift"
"5","2","0","Shift+F5","Key Press","F5","L Shift"
"5","5","0","coach_game_lock","coach_game_lock","",""
"5","7","0","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"5","8","0","Ctrl+G","Key Press","G","L Ctrl"
"5","9","0","Win+Ctrl+D","Key Press","D","L GUI+L Ctrl"
"5","10","0","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"5","9","1","Ctrl+W","Key Press","W","L Ctrl"
"5","0","2","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"5","1","2","Ctrl+S","Key Press","S","L Ctrl"
"5","2","2","Ctrl+J","Key Press","J","L Ctrl"
"5","3","2","Ctrl+Shift+A","Key Press","A","L Ctrl+L Shift"
"5","4","2","Ctrl+Shift+K","Key Press","K","L Ctrl+L Shift"
"5","5","2","Ctrl+Shift+S","Key Press","S","L Ctrl+L Shift"
"5","7","2","Shift+F3","Key Press","F3","L Shift"
"5","10","2","Alt+Shift+D","Key Press","D","L Alt+L Shift"
"5","1","3","Ctrl+Shift+V","Key Press","V","L Ctrl+L Shift"
"5","4","3","Ctrl+S","Key Press","S","L Ctrl"
"5","5","3","F8","Key Press","F8",""
"5","3","4","Base","coach_base","",""
"5","4","4","F9","Key Press","F9",""
"5","5","4","coach_mouse_lock","coach_mouse_lock","",""
"5","7","4","MB5","Mouse Key Press","MB5",""
"5","4","5","Ctrl+G","Key Press","G","L Ctrl"
"5","5","5","Ctrl+;","Key Press","SemiColon and Colon","L Ctrl"
"5","7","5","Ctrl+Shift+!","Key Press","1 and Bang","L Ctrl+L Shift"
"6","3","1","F10","Key Press","F10",""
"6","5","1","Shift+Alt+Up","Key Press","UpArrow","L Shift+L Alt"
"6","7","1","Ctrl+Shift+R","Key Press","R","L Ctrl+L Shift"
"6","9","1","Ctrl+5","Key Press","5 and Percent","L Ctrl"
"6","1","2","Ctrl+Shift+%","Key Press","5 and Percent","L Ctrl+L Shift"
"6","2","2","Ctrl+B","Key Press","B","L Ctrl"
"6","7","2","Alt+Shift++","Key Press","Equals and Plus","L Alt+L Shift"
"6","8","2","Ctrl+4","Key Press","4 and Dollar","L Ctrl"
"6","11","2","Ctrl+O","Key Press","O","L Ctrl"
"6","12","2","Ctrl+Shift+U","Key Press","U","L Ctrl+L Shift"
"6","3","3","Win+R","Key Press","R","L GUI"
"6","5","3","Win+C","Key Press","C","L GUI"
"6","7","3","Ctrl+Shift+I","Key Press","I","L Ctrl+L Shift"
"6","8","3","Ctrl+Shift+T","Key Press","T","L Ctrl+L Shift"
"6","9","3","Ctrl+6","Key Press","6 and Caret","L Ctrl"
"6","10","3","Ctrl+K Ctrl+F","Key Press","F","L Ctrl+K Ctrl"
"6","3","4","Win+V","Key Press","V","L GUI"
"6","4","4","Ctrl+0","Key Press","0 and Right Bracket","L Ctrl"
"6","5","4","Speed","Momentary Layer","Layer::8",""
"6","7","4","Win+Space","Key Press","Spacebar","L GUI"
"6","5","5","Alt+Right","Key Press","RightArrow","L Alt"
"6","7","5","Ctrl+F6","Key Press","F6","L Ctrl"
"7","1","1","9 PU","Key Press","9 and PageUp",""
"7","2","1","↑","Key Press","UpArrow",""
"7","3","1","3 PD","Key Press","3 and PageDn",""
"7","9","1","3 PD","Key Press","3 and PageDn",""
"7","10","1","↑","Key Press","UpArrow",""
"7","11","1","9 PU","Key Press","9 and PageUp",""
"7","1","2","←","Key Press","LeftArrow",""
"7","2","2","↓","Key Press","DownArrow",""
"7","3","2","→","Key Press","RightArrow",""
"7","4","2","Z","Key Press","Z",""
"7","8","2","Z","Key Press","Z",""
"7","9","2","←","Key Press","LeftArrow",""
"7","10","2","↓","Key Press","DownArrow",""
"7","11","2","→","Key Press","RightArrow",""
"7","1","3","X","Key Press","X",""
"7","2","3","C","Key Press","C",""
"7","3","3","Shft","Key Press","LeftShift",""
"7","4","3","Esc","Key Press","Escape",""
"7","8","3","Esc","Key Press","Escape",""
"7","9","3","Shft","Key Press","LeftShift",""
"7","10","3","C","Key Press","C",""
"7","11","3","X","Key Press","X",""
"7","3","4","Exit Base","coach_base","",""
"7","4","4","␣","Key Press","Spacebar",""
"7","5","4","Exit Base","coach_base","",""
"7","7","4","Exit Base","coach_base","",""
"7","8","4","Exit Base","coach_base","",""
"7","4","5","Click","Mouse Key Press","MB1",""
"7","5","5","Right Click","Mouse Key Press","MB2",""
"7","7","5","Ret","Key Press","Return Enter",""
"8","2","1","F11","Key Press","F11",""
"8","0","2","Win+Left","Key Press","LeftArrow","L GUI"
"8","1","2","Win+Right","Key Press","RightArrow","L GUI"
"8","2","2","Ctrl+Shift+F6","Key Press","F6","L Ctrl+L Shift"
"8","3","2","Win+Up","Key Press","UpArrow","L GUI"
"8","4","2","Win+Down","Key Press","DownArrow","L GUI"
"8","5","2","Ctrl+Shift+G","Key Press","G","L Ctrl+L Shift"
"8","7","2","Win+Shift+Right","Key Press","RightArrow","L GUI+L Shift"
"8","8","2","Alt+F4","Key Press","F4","L Alt"
"8","9","2","Win+Ctrl+Left","Key Press","LeftArrow","L GUI+L Ctrl"
"8","10","2","Win+Ctrl+Right","Key Press","RightArrow","L GUI+L Ctrl"
"8","11","2","Win+Ctrl+F4","Key Press","F4","L GUI+L Ctrl"
"8","3","3","Ctrl+Shift+B","Key Press","B","L Ctrl+L Shift"
"8","5","3","Ctrl+Shift+F5","Key Press","F5","L Ctrl+L Shift"
"8","7","3","Ctrl+Tab","Key Press","Tab","L Ctrl"
"8","9","3","Ctrl+Home","Key Press","Home","L Ctrl"
"8","3","4","Ctrl+Shift+`","Key Press","Grave Accent and Tilde","L Ctrl+L Shift"
"8","4","4","Shift+Tab","Key Press","Tab","L Shift"
"8","5","4","Alt+Click","Mouse Key Press","MB1","L Alt"
"8","5","5","F10","Key Press","F10",""
"8","7","5","Alt+Up","Key Press","UpArrow","L Alt"
"9","2","0","Ctrl+Shift+Q","Key Press","Q","L Ctrl+L Shift"
"9","4","0","Shift+Space","Key Press","Spacebar","L Shift"
"9","7","0","Win+Tab","Key Press","Tab","L GUI"
"9","9","0","Shift+Click","Mouse Key Press","MB1","L Shift"
"9","10","0","Ctrl+Z","Key Press","Z","L Ctrl"
"9","0","1","Ctrl+Right","Key Press","RightArrow","L Ctrl"
"9","1","1","Ctrl+2","Key Press","2 and At","L Ctrl"
"9","2","1","Ctrl+Shift+A","Key Press","A","L Ctrl+L Shift"
"9","4","1","Ctrl+M","Key Press","M","L Ctrl"
"9","7","1","Ctrl+P","Key Press","P","L Ctrl"
"9","1","2","Ctrl+Shift+X","Key Press","X","L Ctrl+L Shift"
"9","2","2","Ctrl+Shift+E","Key Press","E","L Ctrl+L Shift"
"9","3","2","Ctrl+N","Key Press","N","L Ctrl"
"9","5","2","Win+X","Key Press","X","L GUI"
"9","7","2","Shift+Alt+Down","Key Press","DownArrow","L Shift+L Alt"
"9","9","2","Ctrl+Alt+Up","Key Press","UpArrow","L Ctrl+L Alt"
"9","10","2","Ctrl+Shift+H","Key Press","H","L Ctrl+L Shift"
"9","11","2","Ctrl+K","Key Press","K","L Ctrl"
"9","12","2","Ctrl+Shift+U","Key Press","U","L Ctrl+L Shift"
"9","1","3","Ctrl+Shift+D","Key Press","D","L Ctrl+L Shift"
"9","2","3","Ctrl+Shift+P","Key Press","P","L Ctrl+L Shift"
"9","3","3","Ctrl+Shift+C","Key Press","C","L Ctrl+L Shift"
"9","4","3","Win+B","Key Press","B","L GUI"
"9","5","3","Win+Shift+Left","Key Press","LeftArrow","L GUI+L Shift"
"9","4","4","Ctrl+O","Key Press","O","L Ctrl"
"9","5","4","Ctrl+Shift+L","Key Press","L","L Ctrl+L Shift"
"9","7","4","MB3","Mouse Key Press","MB3",""
"9","8","4","Win+.","Key Press","Period and GreaterThan","L GUI"
"9","4","5","Ctrl+Alt+Down","Key Press","DownArrow","L Ctrl+L Alt"
"9","7","5","Shift+Alt+Right","Key Press","RightArrow","L Shift+L Alt"
"10","0","0","F5","Key Press","F5",""
"10","1","0","Ctrl+A","Key Press","A","L Ctrl"
"10","2","0","Ctrl+C","Key Press","C","L Ctrl"
"10","3","0","Ctrl+X","Key Press","X","L Ctrl"
"10","4","0","F3","Key Press","F3",""
"10","5","0","F7","Key Press","F7",""
"10","11","0","F1","Key Press","F1",""
"10","12","0","Win+Ctrl+D","Key Press","D","L GUI+L Ctrl"
"10","8","1","Shift+Enter","Key Press","Return Enter","L Shift"
"10","10","1","Ctrl+Shift+Home","Key Press","Home","L Ctrl+L Shift"
"10","11","1","Win+B","Key Press","B","L GUI"
"10","12","1","Ctrl+Left","Key Press","LeftArrow","L Ctrl"
"10","0","2","Ctrl+F","Key Press","F","L Ctrl"
"10","1","2","Alt+=","Key Press","Equals and Plus","L Alt"
"10","2","2","Ctrl+S","Key Press","S","L Ctrl"
"10","3","2","Shift+Alt+Left","Key Press","LeftArrow","L Shift+L Alt"
"10","4","2","Ctrl+Shift+End","Key Press","End","L Ctrl+L Shift"
"10","5","2","F2","Key Press","F2",""
"10","7","2","Win+L","Key Press","L","L GUI"
"10","8","2","Ctrl+V","Key Press","V","L Ctrl"
"10","9","2","Ctrl+Up","Key Press","UpArrow","L Ctrl"
"10","11","2","Win+2","Key Press","2 and At","L GUI"
"10","12","2","Win+N","Key Press","N","L GUI"
"10","0","3","Ctrl+9","Key Press","9 and Left Bracket","L Ctrl"
"10","1","3","Ctrl+H","Key Press","H","L Ctrl"
"10","3","3","Ctrl+Shift+1","Key Press","1 and Bang","L Ctrl+L Shift"
"10","8","3","Win+E","Key Press","E","L GUI"
"10","10","3","F11","Key Press","F11",""
"10","3","4","Base","coach_base","",""
"10","4","4","Ctrl+Shift+Esc","Key Press","Escape","L Ctrl+L Shift"
"10","5","4","Alt+Shift","Key Press","Shift","L Alt"
"10","7","4","Win+T","Key Press","T","L GUI"
"10","8","4","Win+;","Key Press","SemiColon and Colon","L GUI"
"10","4","5","Ctrl+Down","Key Press","DownArrow","L Ctrl"
"10","5","5","Ctrl+]","Key Press","Right Brace","L Ctrl"
"10","7","5","Win+Ctrl+D","Key Press","D","L GUI+L Ctrl"`;

function parseExpected() {
  const lines = EXPECTED_CSV.trim().split('\n');
  const headers = lines[0].split(',').map(h => h.split(String.fromCharCode(34)).join('').trim());
  const out = [];
  for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split(',').map(p => p.split(String.fromCharCode(34)).join('').trim());
    const obj = {};
    for (let j = 0; j < headers.length; j++) obj[headers[j]] = parts[j] || '';
    out.push(obj);
  }
  return out;
}

function runVerify() {
  const expected = parseExpected();
  let pass = 0, fail = 0, errors = [];
  for (const exp of expected) {
    const layer = parseInt(exp.layer);
    const x = parseInt(exp.x);
    const y = parseInt(exp.y);
    const actual = getKeyBinding(layer, x, y);
    if (!actual) {
      fail++;
      errors.push({layer, x, y, expected: exp, error: 'key not found'});
      continue;
    }
    const bMatch = actual.behavior.toLowerCase() === exp.behavior.toLowerCase();
    const pMatch = actual.parameter.toLowerCase() === exp.parameter.toLowerCase();
    const mMatch = actual.modifiers === exp.modifiers;
    if (bMatch && pMatch && mMatch) {
      pass++;
    } else {
      fail++;
      errors.push({layer, x, y, expected: exp, actual});
    }
  }
  console.log('Verify result: ' + pass + ' pass, ' + fail + ' fail (' + (pass/(pass+fail)*100).toFixed(1) + '%)');
  window._CHARYBDIS_VERIFY_RESULT = {pass, fail, errors};
}

runVerify();
